// ─── DUBIMOTORS SHARED DATA & HELPERS ────────────────────────────────────────
// Real listing images fetched directly from the Wix site CDN
// Image base IDs extracted from the live motors listing page

const DM = (() => {

  // Helper to build full-res Wix CDN URL from media hash
  function wix(hash, ext, w, h) {
    return `https://static.wixstatic.com/media/${hash}~mv2.${ext}/v1/fill/w_${w},h_${h},al_c,q_90,enc_avif,quality_auto/${hash}~mv2.${ext}`;
  }

  // Real listings from the Wix site with their actual images
  const listings = [
    // ── CARS ──
    {
      id: 'kia-sportage-2026',
      title: '2026 Kia Sportage Limited Edition',
      category: 'cars',
      make: 'Kia',
      model: 'Sportage',
      trim: 'Limited Edition',
      price: 60000,
      year: 2026,
      km: 0,
      condition: 'Brand New',
      engine: '1.5L Turbo',
      hp: 197,
      cylinders: 4,
      transmission: 'Automatic (8-Speed)',
      bodyType: 'SUV',
      doors: 5,
      seats: 5,
      extColor: 'Steel Grey',
      intColor: 'Black',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Khaled Audi Showroom',
      verified: true,
      // Real image: Kia Sportage grey SUV from the Wix listing
      img: 'https://static.wixstatic.com/media/3789f2_d343a77e170b4500b7b74b2056d5e9b7~mv2.webp/v1/fill/w_600,h_400,al_c,q_90,enc_avif,quality_auto/3789f2_d343a77e170b4500b7b74b2056d5e9b7~mv2.webp',
      regionalSpec: 'GCC Specs',
    },
    {
      id: 'vw-golf-gti-p1rtg',
      title: '2024 Volkswagen Golf GTI P1RTG',
      category: 'cars',
      make: 'Volkswagen',
      model: 'Golf',
      trim: 'GTI P1RTG',
      price: 140000,
      year: 2024,
      km: 5000,
      condition: 'Used',
      engine: '2.0L TSI Turbo',
      hp: 245,
      cylinders: 4,
      transmission: 'Automatic (DSG)',
      bodyType: 'Hatchback',
      doors: 5,
      seats: 5,
      extColor: 'Tornado Red',
      intColor: 'Black/Red',
      warranty: true,
      serviceContract: true,
      location: 'Dubai',
      seller: 'Khaled Audi Showroom',
      verified: true,
      // Real image: VW Golf GTI from the Wix listing
      img: 'https://static.wixstatic.com/media/3789f2_5bd096d1e962457e9dc582a1763fd719~mv2.webp/v1/fill/w_600,h_400,al_c,q_90,enc_avif,quality_auto/3789f2_5bd096d1e962457e9dc582a1763fd719~mv2.webp',
      regionalSpec: 'GCC Specs',
    },
    {
      id: 'vw-golf-gti-p111',
      title: '2024 Volkswagen Golf GTI P111',
      category: 'cars',
      make: 'Volkswagen',
      model: 'Golf',
      trim: 'GTI P111',
      price: 140000,
      year: 2024,
      km: 8200,
      condition: 'Used',
      engine: '2.0L TSI Turbo',
      hp: 245,
      cylinders: 4,
      transmission: 'Automatic (DSG)',
      bodyType: 'Hatchback',
      doors: 5,
      seats: 5,
      extColor: 'Deep Black Pearl',
      intColor: 'Black',
      warranty: false,
      serviceContract: false,
      location: 'Abu Dhabi',
      seller: 'Khaled Audi Showroom',
      verified: true,
      // Real image: VW Golf GTI McLaren edition from the Wix listing
      img: 'https://static.wixstatic.com/media/3789f2_dee12c3603d3457da6c030a90fcc3e66~mv2.jpeg/v1/fill/w_600,h_400,al_c,q_90,enc_avif,quality_auto/3789f2_dee12c3603d3457da6c030a90fcc3e66~mv2.jpeg',
      regionalSpec: 'GCC Specs',
    },
    {
      id: 'harley-buy-now-pay-later',
      title: '2024 Harley-Davidson Road King Special',
      category: 'bikes',
      make: 'Harley-Davidson',
      model: 'Road King',
      trim: 'Special',
      price: 62200,
      year: 2024,
      km: 1200,
      condition: 'Used',
      engine: '1868cc Milwaukee-Eight 114',
      hp: 93,
      cylinders: 2,
      transmission: '6-Speed',
      bodyType: 'Cruiser',
      doors: 0,
      seats: 2,
      extColor: 'Vivid Black',
      intColor: 'Black',
      warranty: false,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Khaled Audi Showroom',
      verified: true,
      regionalSpec: 'GCC Specs',
      // Real image: Harley-Davidson motorcycle from the Wix listing
      img: 'https://static.wixstatic.com/media/3789f2_91c9a2f4e5094bdf80c146853d922fec~mv2.jpeg/v1/fill/w_600,h_400,al_c,q_90,enc_avif,quality_auto/3789f2_91c9a2f4e5094bdf80c146853d922fec~mv2.jpeg',
    },
    {
      id: 'supercar-collection',
      title: '2024 Supercar Collection Dubai',
      category: 'cars',
      make: 'Ferrari',
      model: '488',
      trim: 'Spider',
      price: 50000,
      year: 2024,
      km: 3000,
      condition: 'Used',
      engine: '4.0L V8',
      hp: 660,
      cylinders: 8,
      transmission: 'Automatic',
      bodyType: 'Convertible',
      doors: 2,
      seats: 2,
      extColor: 'Rosso Corsa',
      intColor: 'Beige',
      warranty: false,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Khaled Audi Showroom',
      verified: true,
      // Real image: Ferrari/McLaren beach shot from the Wix listing
      img: 'https://static.wixstatic.com/media/3789f2_9a27396de198461ca15e2be90046d974~mv2.jpeg/v1/fill/w_600,h_400,al_c,q_90,enc_avif,quality_auto/3789f2_9a27396de198461ca15e2be90046d974~mv2.jpeg',
      regionalSpec: 'GCC Specs',
    },
    // ── MOTORCYCLES ──
    {
      id: 'honda-cbr-650-2025',
      title: '2025 Honda CBR 650 E-Clutch',
      category: 'bikes',
      make: 'Honda',
      model: 'CBR 650R',
      trim: 'E-Clutch',
      price: 35000,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '649cc Inline-4',
      hp: 95,
      cylinders: 4,
      transmission: '6-Speed',
      bodyType: 'Sport',
      doors: 0,
      seats: 2,
      extColor: 'Grand Prix Red',
      intColor: 'Black',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Khaled Audi Showroom',
      verified: true,
      regionalSpec: 'GCC Specs',
      // Real image: Honda CBR from the Wix listing
      img: 'https://static.wixstatic.com/media/3789f2_20aa2d7695f240419a43673d77c52bbd~mv2.jpeg/v1/fill/w_600,h_400,al_c,q_90,enc_avif,quality_auto/3789f2_20aa2d7695f240419a43673d77c52bbd~mv2.jpeg',
    },
    // ── JET SKIS ──
    {
      id: 'seadoo-spark-trixx-2025',
      title: '2025 Sea-Doo Spark Trixx',
      category: 'jetski',
      make: 'Sea-Doo',
      model: 'Spark',
      trim: 'Trixx',
      price: 45000,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '900cc Rotax ACE',
      hp: 90,
      cylinders: 3,
      transmission: 'Jet Propulsion',
      bodyType: 'Jet Ski',
      doors: 0,
      seats: 3,
      extColor: 'Fiery Red',
      intColor: 'Black',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Khaled Audi Showroom',
      verified: true,
      regionalSpec: 'GCC Specs',
      // Real image: Sea-Doo jet ski from the Wix listing
      img: 'https://static.wixstatic.com/media/3789f2_69114d68b21f4352b6bd75eaa1367201~mv2.jpeg/v1/fill/w_600,h_400,al_c,q_90,enc_avif,quality_auto/3789f2_69114d68b21f4352b6bd75eaa1367201~mv2.jpeg',
    },
    // ── BOATS ──
    {
      id: 'oceanos-80ft',
      title: 'Oceanos 80ft Luxury Yacht',
      category: 'boats',
      make: 'Oceanos',
      model: '80ft Luxury Yacht',
      trim: 'Custom',
      price: 3550000,
      year: 2022,
      km: 180,
      condition: 'Used',
      engine: '2x Caterpillar C18',
      hp: 2400,
      cylinders: 18,
      transmission: 'Shaft Drive',
      bodyType: 'Motor Yacht',
      doors: 0,
      seats: 12,
      extColor: 'White',
      intColor: 'Cream/Teak',
      warranty: false,
      serviceContract: false,
      location: 'Dubai Marina',
      seller: 'Khaled Audi Showroom',
      verified: true,
      regionalSpec: 'GCC Specs',
      // Real image: Oceanos yacht from the Wix listing
      img: 'https://static.wixstatic.com/media/3789f2_69ec1fe515224d7e8164f12b7a3c19a1~mv2.jpeg/v1/fill/w_600,h_400,al_c,q_90,enc_avif,quality_auto/3789f2_69ec1fe515224d7e8164f12b7a3c19a1~mv2.jpeg',
    },
    {
      id: 'nomad-95-2022',
      title: 'Nomad 95 / 2022 Model / 30 Meters',
      category: 'boats',
      make: 'Nomad',
      model: 'Nomad 95',
      trim: 'Standard',
      price: 2500000,
      year: 2022,
      km: 320,
      condition: 'Used',
      engine: '2x MAN V12',
      hp: 1800,
      cylinders: 12,
      transmission: 'Shaft Drive',
      bodyType: 'Superyacht',
      doors: 0,
      seats: 10,
      extColor: 'White',
      intColor: 'Walnut/Cream',
      warranty: false,
      serviceContract: false,
      location: 'Abu Dhabi',
      seller: 'Khaled Audi Showroom',
      verified: true,
      regionalSpec: 'GCC Specs',
      // Real image: Nomad yacht from the Wix listing
      img: 'https://static.wixstatic.com/media/3789f2_8eec233050b545ea82e15f019b13dc56~mv2.jpeg/v1/fill/w_600,h_400,al_c,q_90,enc_avif,quality_auto/3789f2_8eec233050b545ea82e15f019b13dc56~mv2.jpeg',
    },
    {
      id: 'nomad-95-2022-b',
      title: 'Nomad 95 Superyacht 30M',
      category: 'boats',
      make: 'Nomad',
      model: 'Nomad 95',
      trim: 'Premium',
      price: 2800000,
      year: 2022,
      km: 210,
      condition: 'Used',
      engine: '2x MAN V12 1800hp',
      hp: 1800,
      cylinders: 12,
      transmission: 'Shaft Drive',
      bodyType: 'Superyacht',
      doors: 0,
      seats: 12,
      extColor: 'Pearl White',
      intColor: 'Dark Walnut/Beige',
      warranty: false,
      serviceContract: false,
      location: 'Fujairah',
      seller: 'Khaled Audi Showroom',
      verified: true,
      regionalSpec: 'GCC Specs',
      // Real image: second Nomad yacht from the Wix listing
      img: 'https://static.wixstatic.com/media/3789f2_034af66f42314e9aaddc4142ff0fda06~mv2.jpeg/v1/fill/w_600,h_400,al_c,q_90,enc_avif,quality_auto/3789f2_034af66f42314e9aaddc4142ff0fda06~mv2.jpeg',
    },

    // ── SHARMAX MOTORS UAE LISTINGS ──
    {
      id: 'sharmax-custom-1100-rr-limited-1',
      title: '2025 Sharmax Custom 1100 RR Limited',
      category: 'bikes',
      make: 'Sharmax',
      model: 'Custom 1100 RR Limited',
      trim: 'Standard',
      price: 52990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '1100cc',
      hp: 165,
      cylinders: 4,
      transmission: 'Manual (6-Speed)',
      bodyType: 'Sport',
      doors: 0,
      seats: 1,
      extColor: 'Red',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai Marina',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682c9c37dabd0256125411.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-travel-1000-rr-limited/',
    },
    {
      id: 'sharmax-custom-1000-rst-roadster-2',
      title: '2025 Sharmax Custom 1000 RST Roadster',
      category: 'bikes',
      make: 'Sharmax',
      model: 'Custom 1000 RST Roadster',
      trim: 'Standard',
      price: 47990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '1000cc',
      hp: 150,
      cylinders: 2,
      transmission: 'Manual (6-Speed)',
      bodyType: 'Naked',
      doors: 0,
      seats: 1,
      extColor: 'Blue',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/6827442d38d25426040151.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-custom-1000-rst-roadster/',
    },
    {
      id: 'sharmax-gp-250-competition-3',
      title: '2025 Sharmax GP 250 Competition',
      category: 'bikes',
      make: 'Sharmax',
      model: 'GP 250 Competition',
      trim: 'Standard',
      price: 10590,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '250cc',
      hp: 37,
      cylinders: 1,
      transmission: 'Manual (6-Speed)',
      bodyType: 'Naked',
      doors: 0,
      seats: 1,
      extColor: 'Blue',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Sharjah',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682c963b97bd3597653500.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-super-sport-gp-250-competition/',
    },
    {
      id: 'sharmax-gp-401-ultra-4',
      title: '2025 Sharmax GP 401 Ultra',
      category: 'bikes',
      make: 'Sharmax',
      model: 'GP 401 Ultra',
      trim: 'Standard',
      price: 19990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '401cc',
      hp: 60,
      cylinders: 1,
      transmission: 'Manual (6-Speed)',
      bodyType: 'Naked',
      doors: 0,
      seats: 1,
      extColor: 'Black',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Abu Dhabi',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682c968248c55301185273.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-super-sport-gp-401-ultra/',
    },
    {
      id: 'sharmax-gl-250-dubai-5',
      title: '2025 Sharmax GL 250 Dubai',
      category: 'bikes',
      make: 'Sharmax',
      model: 'GL 250 Dubai',
      trim: 'Standard',
      price: 8590,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '250cc',
      hp: 37,
      cylinders: 1,
      transmission: 'Manual (6-Speed)',
      bodyType: 'Cruiser',
      doors: 0,
      seats: 1,
      extColor: 'Blue',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/68274646321db634949785.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-touring-bike-gl-250/',
    },
    {
      id: 'sharmax-gl-400-6',
      title: '2025 Sharmax GL 400',
      category: 'bikes',
      make: 'Sharmax',
      model: 'GL 400',
      trim: 'Standard',
      price: 11990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '400cc',
      hp: 60,
      cylinders: 1,
      transmission: 'Manual (6-Speed)',
      bodyType: 'Sport',
      doors: 0,
      seats: 1,
      extColor: 'Black',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Sharjah',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682746d3bedae931439314.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-touring-bike-gl-400/',
    },
    {
      id: 'sharmax-enduro-250-travel-7',
      title: '2025 Sharmax Enduro 250 Travel',
      category: 'bikes',
      make: 'Sharmax',
      model: 'Enduro 250 Travel',
      trim: 'Standard',
      price: 6990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '250cc',
      hp: 37,
      cylinders: 1,
      transmission: 'Manual (6-Speed)',
      bodyType: 'Cruiser',
      doors: 0,
      seats: 1,
      extColor: 'Green',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Sharjah',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/6827446e7e4bf842911729.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-enduro-travel-250/',
    },
    {
      id: 'sharmax-enduro-300-travel-8',
      title: '2025 Sharmax Enduro 300 Travel',
      category: 'bikes',
      make: 'Sharmax',
      model: 'Enduro 300 Travel',
      trim: 'Standard',
      price: 7590,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '300cc',
      hp: 45,
      cylinders: 1,
      transmission: 'Manual (6-Speed)',
      bodyType: 'Touring',
      doors: 0,
      seats: 1,
      extColor: 'Blue',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai Marina',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682744a4590fd214190431.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-enduro-travel-300/',
    },
    {
      id: 'sharmax-gl-770-ultra-9',
      title: '2025 Sharmax GL 770 Ultra',
      category: 'bikes',
      make: 'Sharmax',
      model: 'GL 770 Ultra',
      trim: 'Standard',
      price: 27990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '770cc',
      hp: 115,
      cylinders: 1,
      transmission: 'Manual (6-Speed)',
      bodyType: 'Adventure',
      doors: 0,
      seats: 1,
      extColor: 'Orange',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/6827474de54e7335433898.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-touring-bike-gl-770-ultra/',
    },
    {
      id: 'sharmax-fx-200-10',
      title: '2025 Sharmax FX 200',
      category: 'bikes',
      make: 'Sharmax',
      model: 'FX 200',
      trim: 'Standard',
      price: 5990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '200cc',
      hp: 30,
      cylinders: 1,
      transmission: 'Manual (6-Speed)',
      bodyType: 'Adventure',
      doors: 0,
      seats: 1,
      extColor: 'Red',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682745dec509b916008682.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/maxi-scooter-sharmax-fx-200/',
    },
    {
      id: 'sharmax-rr-250-11',
      title: '2025 Sharmax RR 250',
      category: 'bikes',
      make: 'Sharmax',
      model: 'RR 250',
      trim: 'Standard',
      price: 7990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '250cc',
      hp: 37,
      cylinders: 1,
      transmission: 'Manual (6-Speed)',
      bodyType: 'Naked',
      doors: 0,
      seats: 1,
      extColor: 'Blue',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Abu Dhabi',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682c98ad9fa59143257323.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-road-bike-rr-250/',
    },
    {
      id: 'sharmax-fx-150-ultra-efi-12',
      title: '2025 Sharmax FX 150 Ultra EFI',
      category: 'bikes',
      make: 'Sharmax',
      model: 'FX 150 Ultra EFI',
      trim: 'Standard',
      price: 11990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '150cc',
      hp: 22,
      cylinders: 1,
      transmission: 'Manual (6-Speed)',
      bodyType: 'Adventure',
      doors: 0,
      seats: 1,
      extColor: 'Green',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Abu Dhabi',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/6827459f50a4e306319712.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-maxi-scooter-fx-150-ultra/',
    },
    {
      id: 'sharmax-rr-551-ultra-13',
      title: '2025 Sharmax RR 551 Ultra',
      category: 'bikes',
      make: 'Sharmax',
      model: 'RR 551 Ultra',
      trim: 'Standard',
      price: 23190,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '551cc',
      hp: 82,
      cylinders: 1,
      transmission: 'Manual (6-Speed)',
      bodyType: 'Touring',
      doors: 0,
      seats: 1,
      extColor: 'Blue',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Jumeirah',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682c99835421f353936724.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-road-bike-rr-551-ultra/',
    },
    {
      id: 'sharmax-rst-322-ultra-14',
      title: '2025 Sharmax RST 322 Ultra',
      category: 'bikes',
      make: 'Sharmax',
      model: 'RST 322 Ultra',
      trim: 'Standard',
      price: 14990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '322cc',
      hp: 48,
      cylinders: 1,
      transmission: 'Manual (6-Speed)',
      bodyType: 'Cruiser',
      doors: 0,
      seats: 1,
      extColor: 'Black',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682c9b1430cf9837319837.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-naked-bike-rst-322-ultra/',
    },
    {
      id: 'sharmax-rst-150-ultra-15',
      title: '2025 Sharmax RST 150 Ultra',
      category: 'bikes',
      make: 'Sharmax',
      model: 'RST 150 Ultra',
      trim: 'Standard',
      price: 4990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '150cc',
      hp: 22,
      cylinders: 1,
      transmission: 'Manual (6-Speed)',
      bodyType: 'Sport',
      doors: 0,
      seats: 1,
      extColor: 'Blue',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai Marina',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682c99f1a0e25661548800.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-naked-bike-rst-150-ultra/',
    },
    {
      id: 'sharmax-rst-750-ultra-16',
      title: '2025 Sharmax RST 750 Ultra',
      category: 'bikes',
      make: 'Sharmax',
      model: 'RST 750 Ultra',
      trim: 'Standard',
      price: 22990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '750cc',
      hp: 112,
      cylinders: 1,
      transmission: 'Manual (6-Speed)',
      bodyType: 'Touring',
      doors: 0,
      seats: 1,
      extColor: 'Black',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682c9b73ec327178111119.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-naked-bike-rst-750-ultra/',
    },
    {
      id: 'sharmax-rst-422-ultra-17',
      title: '2025 Sharmax RST 422 Ultra',
      category: 'bikes',
      make: 'Sharmax',
      model: 'RST 422 Ultra',
      trim: 'Standard',
      price: 17990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '422cc',
      hp: 63,
      cylinders: 2,
      transmission: 'Manual (6-Speed)',
      bodyType: 'Sport',
      doors: 0,
      seats: 1,
      extColor: 'Red',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682c9b4201fb3511376300.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-naked-bike-rst-422-ultra/',
    },
    {
      id: 'sharmax-fx-350-ultra-18',
      title: '2025 Sharmax FX 350 Ultra',
      category: 'bikes',
      make: 'Sharmax',
      model: 'FX 350 Ultra',
      trim: 'Standard',
      price: 20900,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '350cc',
      hp: 52,
      cylinders: 1,
      transmission: 'Manual (6-Speed)',
      bodyType: 'Touring',
      doors: 0,
      seats: 1,
      extColor: 'Green',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai Marina',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/68274614c514f805216113.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-maxi-scooter-fx-350-ultra/',
    },
    {
      id: 'sharmax-sport-250-19',
      title: '2025 Sharmax Sport 250',
      category: 'bikes',
      make: 'Sharmax',
      model: 'Sport 250',
      trim: 'Standard',
      price: 7990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '250cc',
      hp: 30,
      cylinders: 1,
      transmission: 'Manual (5-Speed)',
      bodyType: 'Trail',
      doors: 0,
      seats: 1,
      extColor: 'Orange',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai Marina',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/68cd615c9dc3c057720403.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-sport-250/',
    },
    {
      id: 'sharmax-power-max-250-20',
      title: '2025 Sharmax Power Max 250',
      category: 'bikes',
      make: 'Sharmax',
      model: 'Power Max 250',
      trim: 'Standard',
      price: 8490,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '250cc',
      hp: 30,
      cylinders: 1,
      transmission: 'Manual (5-Speed)',
      bodyType: 'Trail',
      doors: 0,
      seats: 1,
      extColor: 'Red',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Sharjah',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682c9816b29d1244489132.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-power-max-250/',
    },
    {
      id: 'sharmax-power-max-320-21',
      title: '2025 Sharmax Power Max 320',
      category: 'bikes',
      make: 'Sharmax',
      model: 'Power Max 320',
      trim: 'Standard',
      price: 10590,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '320cc',
      hp: 38,
      cylinders: 1,
      transmission: 'Manual (5-Speed)',
      bodyType: 'Pitbike',
      doors: 0,
      seats: 1,
      extColor: 'Orange',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682c987a357dc259225792.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-power-max-320/',
    },
    {
      id: 'sharmax-expert-pro-450-22',
      title: '2025 Sharmax Expert Pro 450',
      category: 'bikes',
      make: 'Sharmax',
      model: 'Expert Pro 450',
      trim: 'Standard',
      price: 17990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '450cc',
      hp: 54,
      cylinders: 2,
      transmission: 'Manual (5-Speed)',
      bodyType: 'Pitbike',
      doors: 0,
      seats: 1,
      extColor: 'Black',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/6827453c1c7c7749683107.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-expert-pro-rxp-450/',
    },
    {
      id: 'sharmax-power-max-190-23',
      title: '2025 Sharmax Power Max 190',
      category: 'bikes',
      make: 'Sharmax',
      model: 'Power Max 190',
      trim: 'Standard',
      price: 5490,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '190cc',
      hp: 22,
      cylinders: 1,
      transmission: 'Manual (5-Speed)',
      bodyType: 'Pitbike',
      doors: 0,
      seats: 1,
      extColor: 'Red',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/68dabb0f077d6850832562.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-power-max-190/',
    },
    {
      id: 'sharmax-power-max-145-24',
      title: '2025 Sharmax Power Max 145',
      category: 'bikes',
      make: 'Sharmax',
      model: 'Power Max 145',
      trim: 'Standard',
      price: 4990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '145cc',
      hp: 17,
      cylinders: 1,
      transmission: 'Manual (5-Speed)',
      bodyType: 'Motocross',
      doors: 0,
      seats: 1,
      extColor: 'Blue',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Abu Dhabi',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/68fb6e2930f48656202776.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-power-max-145-1/',
    },
    {
      id: 'sharmax-expert-pro-320-25',
      title: '2025 Sharmax Expert Pro 320',
      category: 'bikes',
      make: 'Sharmax',
      model: 'Expert Pro 320',
      trim: 'Standard',
      price: 14990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '320cc',
      hp: 38,
      cylinders: 1,
      transmission: 'Manual (5-Speed)',
      bodyType: 'Pitbike',
      doors: 0,
      seats: 1,
      extColor: 'Green',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/68cd848836304440123027.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/expert-pro-320/',
    },
    {
      id: 'sharmax-expert-pro-300-2t-husq-edition-26',
      title: '2025 Sharmax Expert Pro 300 2t Husq Edition',
      category: 'bikes',
      make: 'Sharmax',
      model: 'Expert Pro 300 2t Husq Edition',
      trim: 'Standard',
      price: 24990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '300cc',
      hp: 36,
      cylinders: 1,
      transmission: 'Manual (5-Speed)',
      bodyType: 'Motocross',
      doors: 0,
      seats: 1,
      extColor: 'Red',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/68d6a5c977fd0386994184.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/expert-pro-300-2t/',
    },
    {
      id: 'sharmax-sport-130-mini-27',
      title: '2025 Sharmax Sport 130 Mini',
      category: 'bikes',
      make: 'Sharmax',
      model: 'Sport 130 Mini',
      trim: 'Standard',
      price: 4190,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '130cc',
      hp: 15,
      cylinders: 1,
      transmission: 'Manual (5-Speed)',
      bodyType: 'Enduro',
      doors: 0,
      seats: 1,
      extColor: 'Orange',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/6967908c73113806499884.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sport-130-mini/',
    },
    {
      id: 'sharmax-cruiser-race-350-gx-28',
      title: '2025 Sharmax Cruiser Race 350 GX',
      category: 'heavy',
      make: 'Sharmax',
      model: 'Cruiser Race 350 GX',
      trim: 'Standard',
      price: 11490,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '350cc',
      hp: 28,
      cylinders: 1,
      transmission: 'CVT Automatic',
      bodyType: 'Quad Bike',
      doors: 0,
      seats: 1,
      extColor: 'Black',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Sharjah',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/6825ef08146ea335049195.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-350-gx-cruiser/',
    },
    {
      id: 'sharmax-force-650-efi-eps-29',
      title: '2025 Sharmax Force 650 EFI EPS',
      category: 'heavy',
      make: 'Sharmax',
      model: 'Force 650 EFI EPS',
      trim: 'Standard',
      price: 22990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '650cc',
      hp: 52,
      cylinders: 2,
      transmission: 'CVT Automatic',
      bodyType: 'ATV',
      doors: 0,
      seats: 1,
      extColor: 'Orange',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/68d163157ef7f128620887.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-650-force/',
    },
    {
      id: 'sharmax-hummer-320-rx-ltd-30',
      title: '2025 Sharmax Hummer 320 RX LTD',
      category: 'heavy',
      make: 'Sharmax',
      model: 'Hummer 320 RX LTD',
      trim: 'Standard',
      price: 11990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '320cc',
      hp: 25,
      cylinders: 1,
      transmission: 'CVT Automatic',
      bodyType: 'ATV',
      doors: 0,
      seats: 1,
      extColor: 'Green',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/68d1639f006dc786028992.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-hummer-320-rx/',
    },
    {
      id: 'sharmax-cruiser-300-fj-31',
      title: '2025 Sharmax Cruiser 300 FJ',
      category: 'heavy',
      make: 'Sharmax',
      model: 'Cruiser 300 FJ',
      trim: 'Standard',
      price: 10490,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '300cc',
      hp: 24,
      cylinders: 1,
      transmission: 'CVT Automatic',
      bodyType: 'ATV',
      doors: 0,
      seats: 1,
      extColor: 'Red',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/6825efde5c4d1620449154.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-300-fj-cruiser/',
    },
    {
      id: 'sharmax-force-1100-efi-eps-32',
      title: '2025 Sharmax Force 1100 EFI EPS',
      category: 'heavy',
      make: 'Sharmax',
      model: 'Force 1100 EFI EPS',
      trim: 'Standard',
      price: 41990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '1100cc',
      hp: 88,
      cylinders: 4,
      transmission: 'CVT Automatic',
      bodyType: 'ATV',
      doors: 0,
      seats: 1,
      extColor: 'Green',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Sharjah',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/68f76dd9681a6202957510.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-1100-force/',
    },
    {
      id: 'sharmax-cruiser-race-550-gx-33',
      title: '2025 Sharmax Cruiser Race 550 GX',
      category: 'heavy',
      make: 'Sharmax',
      model: 'Cruiser Race 550 GX',
      trim: 'Standard',
      price: 17990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '550cc',
      hp: 44,
      cylinders: 1,
      transmission: 'CVT Automatic',
      bodyType: 'ATV',
      doors: 0,
      seats: 1,
      extColor: 'Red',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/6825ef3629508319286321.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-550-gx-cruiser/',
    },
    {
      id: 'sharmax-cross-180-rx-34',
      title: '2025 Sharmax Cross 180 RX',
      category: 'heavy',
      make: 'Sharmax',
      model: 'Cross 180 RX',
      trim: 'Standard',
      price: 5490,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '180cc',
      hp: 14,
      cylinders: 1,
      transmission: 'CVT Automatic',
      bodyType: 'Quad Bike',
      doors: 0,
      seats: 1,
      extColor: 'Black',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/69429b2adefe7777508420.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/cross-180-rx/',
    },
    {
      id: 'sharmax-activator-280-rx-35',
      title: '2025 Sharmax Activator 280 RX',
      category: 'heavy',
      make: 'Sharmax',
      model: 'Activator 280 RX',
      trim: 'Standard',
      price: 8990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '280cc',
      hp: 22,
      cylinders: 1,
      transmission: 'CVT Automatic',
      bodyType: 'Quad Bike',
      doors: 0,
      seats: 1,
      extColor: 'Orange',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Abu Dhabi',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/68cd490a8eb96462679183.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/activator-280-rx/',
    },
    {
      id: 'sharmax-raizer-250-race-cup-36',
      title: '2025 Sharmax Raizer 250 Race Cup',
      category: 'heavy',
      make: 'Sharmax',
      model: 'Raizer 250 Race Cup',
      trim: 'Standard',
      price: 9490,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '250cc',
      hp: 20,
      cylinders: 1,
      transmission: 'CVT Automatic',
      bodyType: 'ATV',
      doors: 0,
      seats: 1,
      extColor: 'Red',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Abu Dhabi',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/68db8cdb62096198208444.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/raizer-250-race-cup/',
    },
    {
      id: 'sharmax-cross-130-37',
      title: '2025 Sharmax Cross 130',
      category: 'heavy',
      make: 'Sharmax',
      model: 'Cross 130',
      trim: 'Standard',
      price: 3990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '130cc',
      hp: 10,
      cylinders: 1,
      transmission: 'CVT Automatic',
      bodyType: 'ATV',
      doors: 0,
      seats: 1,
      extColor: 'Red',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/68d51d4d3eb65555330215.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/cross-130/',
    },
    {
      id: 'sharmax-jump-1100-2-seater-38',
      title: '2025 Sharmax Jump 1100 2 seater',
      category: 'heavy',
      make: 'Sharmax',
      model: 'Jump 1100 2 seater',
      trim: 'Standard',
      price: 49990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '1100cc',
      hp: 88,
      cylinders: 2,
      transmission: 'CVT Automatic',
      bodyType: 'UTV',
      doors: 0,
      seats: 2,
      extColor: 'Red',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai Marina',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/6825f12ae1d3d215686224.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-1100-rx-jump-2-seater/',
    },
    {
      id: 'sharmax-junior-250-39',
      title: '2025 Sharmax Junior 250',
      category: 'heavy',
      make: 'Sharmax',
      model: 'Junior 250',
      trim: 'Standard',
      price: 13490,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '250cc',
      hp: 20,
      cylinders: 1,
      transmission: 'CVT Automatic',
      bodyType: 'UTV',
      doors: 0,
      seats: 2,
      extColor: 'Green',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Sharjah',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/6826ecd3dab14060588463.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-junior-250/',
    },
    {
      id: 'sharmax-predator-420-2-seater-40',
      title: '2025 Sharmax Predator 420 2 seater',
      category: 'heavy',
      make: 'Sharmax',
      model: 'Predator 420 2 seater',
      trim: 'Standard',
      price: 21990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '420cc',
      hp: 33,
      cylinders: 2,
      transmission: 'CVT Automatic',
      bodyType: 'UTV',
      doors: 0,
      seats: 4,
      extColor: 'Green',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Abu Dhabi',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/6826ed0270e51050497107.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-predator-420-2-seater/',
    },
    {
      id: 'sharmax-race-580-41',
      title: '2025 Sharmax Race 580',
      category: 'heavy',
      make: 'Sharmax',
      model: 'Race 580',
      trim: 'Standard',
      price: 29990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '580cc',
      hp: 46,
      cylinders: 2,
      transmission: 'CVT Automatic',
      bodyType: 'Buggy',
      doors: 0,
      seats: 2,
      extColor: 'Blue',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/6825f101b5b22334618424.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-580-race/',
    },
    {
      id: 'sharmax-junior-200-pro-42',
      title: '2025 Sharmax Junior 200 PRO',
      category: 'heavy',
      make: 'Sharmax',
      model: 'Junior 200 PRO',
      trim: 'Standard',
      price: 6990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '200cc',
      hp: 16,
      cylinders: 1,
      transmission: 'CVT Automatic',
      bodyType: 'UTV',
      doors: 0,
      seats: 2,
      extColor: 'White',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/6825f07376346495775582.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/junior-200-pro/',
    },
    {
      id: 'sharmax-xforce-1100-sport-x2-43',
      title: '2025 Sharmax XForce 1100 Sport x2',
      category: 'heavy',
      make: 'Sharmax',
      model: 'XForce 1100 Sport x2',
      trim: 'Standard',
      price: 56990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '1100cc',
      hp: 88,
      cylinders: 2,
      transmission: 'CVT Automatic',
      bodyType: 'Side-by-Side',
      doors: 0,
      seats: 2,
      extColor: 'Blue',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/6952e3f83170f668619180.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/xforce-1100/',
    },
    {
      id: 'sharmax-5000-2plus2-seater-44',
      title: '2025 Sharmax 5000 2+2 Seater',
      category: 'heavy',
      make: 'Sharmax',
      model: '5000 2+2 Seater',
      trim: 'Standard',
      price: 25990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: 'Electric Motor',
      hp: 7,
      cylinders: 0,
      transmission: 'Electric Drive',
      bodyType: 'Electric Cart',
      doors: 0,
      seats: 2,
      extColor: 'Blue',
      intColor: 'Black',
      fuelType: 'Electric',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/6826ed31be73e096857416.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-golf-cart-5000-4-seater/',
    },
    {
      id: 'sharmax-5000-4-seater-pro-45',
      title: '2025 Sharmax 5000 4 Seater Pro',
      category: 'heavy',
      make: 'Sharmax',
      model: '5000 4 Seater Pro',
      trim: 'Standard',
      price: 28990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: 'Electric Motor',
      hp: 10,
      cylinders: 0,
      transmission: 'Electric Drive',
      bodyType: 'Golf Cart',
      doors: 0,
      seats: 4,
      extColor: 'Grey',
      intColor: 'Black',
      fuelType: 'Electric',
      warranty: true,
      serviceContract: false,
      location: 'Abu Dhabi',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/6826ed599a522433479767.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-golf-cart-5000-4-seater-pro/',
    },
    {
      id: 'sharmax-5000-6-seater-pro-46',
      title: '2025 Sharmax 5000 6 Seater Pro',
      category: 'heavy',
      make: 'Sharmax',
      model: '5000 6 Seater Pro',
      trim: 'Standard',
      price: 32990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: 'Electric Motor',
      hp: 10,
      cylinders: 0,
      transmission: 'Electric Drive',
      bodyType: 'Golf Cart',
      doors: 0,
      seats: 6,
      extColor: 'Grey',
      intColor: 'Black',
      fuelType: 'Electric',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/6826ed8738853947330495.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-golf-cart-5000-4-plus-2-seater/',
    },
    {
      id: 'sharmax-cross-e-200-47',
      title: '2025 Sharmax Cross E-200',
      category: 'bikes',
      make: 'Sharmax',
      model: 'Cross E-200',
      trim: 'Standard',
      price: 4590,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: 'Electric Motor',
      hp: 7,
      cylinders: 0,
      transmission: 'Electric Drive',
      bodyType: 'Electric Pitbike',
      doors: 0,
      seats: 1,
      extColor: 'Yellow',
      intColor: 'Black',
      fuelType: 'Electric',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/68cd40039f431631094062.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-e-200-cross/',
    },
    {
      id: 'sharmax-electric-s1-190-48',
      title: '2025 Sharmax Electric S1 190',
      category: 'bikes',
      make: 'Sharmax',
      model: 'Electric S1 190',
      trim: 'Standard',
      price: 4990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: 'Electric Motor',
      hp: 15,
      cylinders: 0,
      transmission: 'Electric Drive',
      bodyType: 'Electric Pitbike',
      doors: 0,
      seats: 1,
      extColor: 'Black',
      intColor: 'Black',
      fuelType: 'Electric',
      warranty: true,
      serviceContract: false,
      location: 'Jumeirah',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682c924d86068429531579.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-electro-expert-pro-190-s1/',
    },
    {
      id: 'sharmax-x5-pro-e-49',
      title: '2025 Sharmax X5 Pro E',
      category: 'bikes',
      make: 'Sharmax',
      model: 'X5 Pro E',
      trim: 'Standard',
      price: 11990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: 'Electric Motor',
      hp: 10,
      cylinders: 0,
      transmission: 'Electric Drive',
      bodyType: 'Electric Sport',
      doors: 0,
      seats: 1,
      extColor: 'White',
      intColor: 'Black',
      fuelType: 'Electric',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682c9c6c3527d508503406.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-x5-pro-electro/',
    },
    {
      id: 'sharmax-luxe-420-50',
      title: '2025 Sharmax Luxe 420',
      category: 'boats',
      make: 'Sharmax',
      model: 'Luxe 420',
      trim: 'Standard',
      price: 12990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '420cc',
      hp: 33,
      cylinders: 1,
      transmission: 'N/A',
      bodyType: 'Outboard Motor',
      doors: 0,
      seats: 0,
      extColor: 'Navy Blue',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/67d47ee7eab9e597082707.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-stormline-luxe-420/',
    },
    {
      id: 'sharmax-luxe-500-51',
      title: '2025 Sharmax Luxe 500',
      category: 'boats',
      make: 'Sharmax',
      model: 'Luxe 500',
      trim: 'Standard',
      price: 11990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '500cc',
      hp: 40,
      cylinders: 1,
      transmission: 'N/A',
      bodyType: 'Outboard Motor',
      doors: 0,
      seats: 0,
      extColor: 'Grey',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Abu Dhabi',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/67d47f3a1387d900618714.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-stormline-luxe-500/',
    },
    {
      id: 'sharmax-standart-400-console-52',
      title: '2025 Sharmax Standart 400 Console',
      category: 'boats',
      make: 'Sharmax',
      model: 'Standart 400 Console',
      trim: 'Standard',
      price: 9990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '400cc',
      hp: 32,
      cylinders: 2,
      transmission: 'N/A',
      bodyType: 'Inflatable Boat',
      doors: 0,
      seats: 0,
      extColor: 'Black',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/67d47f789c061813425211.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-stormline-standart-400-console/',
    },
    {
      id: 'sharmax-mf60fel-t-efi-53',
      title: '2025 Sharmax MF60FEL-T EFI',
      category: 'boats',
      make: 'Sharmax',
      model: 'MF60FEL-T EFI',
      trim: 'Standard',
      price: 19990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '60cc',
      hp: 10,
      cylinders: 1,
      transmission: 'N/A',
      bodyType: 'Outboard Motor',
      doors: 0,
      seats: 0,
      extColor: 'White',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682dc3c5b624a750909861.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-4-stroke-outboard-mikatsu-mf60fel-t-efi/',
    },
    {
      id: 'sharmax-mf115fel-t-54',
      title: '2025 Sharmax MF115FEL-T',
      category: 'boats',
      make: 'Sharmax',
      model: 'MF115FEL-T',
      trim: 'Standard',
      price: 32990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '115cc',
      hp: 10,
      cylinders: 1,
      transmission: 'N/A',
      bodyType: 'Inflatable Boat',
      doors: 0,
      seats: 0,
      extColor: 'Navy Blue',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682dc3f6341e5010795445.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-4-stroke-outboard-mikatsu-mf115fel-t-efi/',
    },
    {
      id: 'sharmax-mf40fel-t-efi-55',
      title: '2025 Sharmax MF40FEL-T EFI',
      category: 'boats',
      make: 'Sharmax',
      model: 'MF40FEL-T EFI',
      trim: 'Standard',
      price: 16990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: 'N/A',
      hp: 15,
      cylinders: 1,
      transmission: 'N/A',
      bodyType: 'Inflatable Boat',
      doors: 0,
      seats: 0,
      extColor: 'Navy Blue',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682dc3ae0b2b6745211894.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/marine-sharmax-4-stroke-outboard-mikatsu/',
    },
    {
      id: 'sharmax-mf90fel-t-56',
      title: '2025 Sharmax MF90FEL-T',
      category: 'boats',
      make: 'Sharmax',
      model: 'MF90FEL-T',
      trim: 'Standard',
      price: 15990,
      year: 2025,
      km: 0,
      condition: 'Brand New',
      engine: '90cc',
      hp: 10,
      cylinders: 1,
      transmission: 'N/A',
      bodyType: 'Inflatable Boat',
      doors: 0,
      seats: 0,
      extColor: 'Black',
      intColor: 'Black',
      fuelType: 'Gasoline',
      warranty: true,
      serviceContract: false,
      location: 'Dubai',
      seller: 'Sharmax Motors UAE',
      verified: true,
      img: 'https://cdn.sharmax.com/cdn-cgi/image/anim=false,dpr=1,fit=scale-down,quality=85,width=440,format=auto/ae/images/media/682dc3dfc7369182614896.png',
      regionalSpec: 'GCC Specs',
      sharmax_url: 'https://sharmax.com/ae_en/product/sharmax-2-stroke-outboard-mikatsu/',
    },
  ];

  function formatPrice(p) {
    return 'AED ' + p.toLocaleString();
  }

  function getCounts() {
    const cars   = listings.filter(l => l.category === 'cars').length;
    const boats  = listings.filter(l => l.category === 'boats' || l.category === 'jetski').length;
    const bikes  = listings.filter(l => l.category === 'bikes').length;
    const jetski = listings.filter(l => l.category === 'jetski').length;
    const heavy  = listings.filter(l => l.category === 'heavy').length;
    return { total: listings.length, cars, boats, bikes, jetski, heavy };
  }

  function getByCategory(cat) {
    if (!cat || cat === 'all') return listings;
    return listings.filter(l => l.category === cat);
  }

  function getById(id) {
    return listings.find(l => l.id === id) || null;
  }

  function renderCard(l) {
    return `
      <div class="listing-card" onclick="window.location.href='listing.html?id=${l.id}'">
        <div class="card-img-wrap">
          <img src="${l.img}" alt="${l.title}" loading="lazy" />
          <span class="card-badge ${l.condition === 'Brand New' ? 'badge-new' : 'badge-used'}">${l.condition}</span>
          ${l.verified ? '<span class="card-verified">✓ Verified</span>' : ''}
        </div>
        <div class="card-body">
          <div class="card-price">${formatPrice(l.price)}</div>
          <div class="card-title">${l.title}</div>
          <div class="card-pills">
            <span class="pill">${l.year}</span>
            <span class="pill">${l.km === 0 ? '0 KM' : l.km.toLocaleString() + ' KM'}</span>
            <span class="pill">${l.regionalSpec || 'GCC Specs'}</span>
          </div>
          <div class="card-location">📍 ${l.location}</div>
        </div>
        <div class="card-footer">
          <div class="card-seller">${l.seller}</div>
          <button class="btn-sm-orange" onclick="event.stopPropagation();window.location.href='listing.html?id=${l.id}'">Details</button>
        </div>
      </div>`;
  }

  return { listings, formatPrice, getCounts, getByCategory, getById, renderCard };
})();
