/* ─── DUBIMOTORS VEHICLE DATABASE ───────────────────────────────────────────
   Full Brand / Model / Trim data for Cars, Boats, Motorcycles, Jet Skis
   Sourced from UAE market data (Dubizzle, AutoTrader, CarSwitch)
   ─────────────────────────────────────────────────────────────────────────── */

const DM_VEHICLES = {

  /* ══════════════════════════════════════════════════════════════════════════
     CARS
  ══════════════════════════════════════════════════════════════════════════ */
  cars: {
    "Acura": {
      "MDX": ["Base", "Technology", "A-Spec", "Advance", "Type S", "Type S Advance"],
      "RDX": ["Base", "Technology", "A-Spec", "Advance"],
      "TLX": ["Base", "Technology", "A-Spec", "Advance", "Type S", "Type S Advance"],
      "Integra": ["Base", "A-Spec", "A-Spec Technology", "Type S"],
      "NSX": ["Coupe", "Type S"],
      "ZDX": ["A-Spec", "Type S"],
      "Other": ["Specify in title/description"]
    },
    "Alfa Romeo": {
      "Giulia": ["Sprint", "Ti", "Veloce", "Quadrifoglio"],
      "Stelvio": ["Sprint", "Ti", "Veloce", "Quadrifoglio"],
      "Tonale": ["Sprint", "Ti", "Veloce"],
      "4C": ["Coupe", "Spider"],
      "Other": ["Specify in title/description"]
    },
    "Aston Martin": {
      "DB11": ["V8", "V12", "AMR"],
      "DBS": ["Superleggera", "770 Ultimate"],
      "DBX": ["Standard", "707"],
      "Vantage": ["Standard", "F1 Edition", "AMR"],
      "Vanquish": ["Standard", "S", "Zagato"],
      "Rapide": ["Standard", "S", "AMR"],
      "DB12": ["Coupe", "Volante"],
      "DB9": ["Coupe", "Volante", "GT"],
      "DB7": ["Vantage", "GT", "Volante", "Zagato"],
      "Valkyrie": ["Coupe", "Spider", "AMR Pro"],
      "Valhalla": ["Standard"],
      "Valour": ["Standard"],
      "Valiant": ["Standard"],
      "One-77": ["Standard"],
      "Vulcan": ["Standard", "AMR Pro"],
      "Cygnet": ["Standard", "V8"],
      "Virage": ["Coupe", "Volante", "Shooting Brake"],
      "Lagonda": ["Standard", "Taraf"],
      "V8 Vantage": ["Standard", "S", "V12", "V12 S"],
      "V12 Vantage": ["Coupe", "Roadster"],
      "Other": ["Specify in title/description"]
    },
    "Audi": {
      "A3": ["30 TFSI", "35 TFSI", "40 TFSI", "45 TFSI e", "S3", "RS3"],
      "A4": ["35 TFSI", "40 TFSI", "45 TFSI", "S4", "RS4"],
      "A5": ["35 TFSI", "40 TFSI", "45 TFSI", "S5", "RS5"],
      "A6": ["40 TFSI", "45 TFSI", "55 TFSI", "S6", "RS6"],
      "A7": ["45 TFSI", "55 TFSI", "S7", "RS7"],
      "A8": ["50 TDI", "55 TFSI", "60 TFSI e", "L", "S8"],
      "Q2": ["30 TFSI", "35 TFSI", "40 TFSI"],
      "Q3": ["35 TFSI", "40 TFSI", "45 TFSI", "RS Q3"],
      "Q5": ["40 TFSI", "45 TFSI", "55 TFSI e", "SQ5", "RS Q5"],
      "Q7": ["45 TFSI", "55 TFSI", "SQ7"],
      "Q8": ["50 TDI", "55 TFSI", "SQ8", "RS Q8"],
      "e-tron": ["50", "55", "S", "GT", "GT RS"],
      "TT": ["TTS Coupe", "TTS Roadster", "TT RS", "Coupe", "Roadster", "TTS", "Final Edition"],
      "R8": ["V10 Performance", "V10 Performance Spyder", "V8", "V10", "V10 Plus", "GT", "Spyder", "Final Edition"],
      "S3": ["Sedan", "Sportback"],
      "RS3": ["Sedan", "Sportback", "Performance"],
      "S4": ["Sedan", "Avant"],
      "RS4": ["Avant", "Cabriolet"],
      "S5": ["Coupe", "Sportback", "Cabriolet"],
      "RS5": ["Coupe", "Sportback", "Cabriolet"],
      "S6": ["Sedan", "Avant"],
      "RS6": ["Avant", "Performance"],
      "S7": ["Sportback"],
      "RS7": ["Sportback", "Performance"],
      "S8": ["Standard", "Plus"],
      "SQ5": ["Standard", "Sportback", "TDI"],
      "SQ7": ["Standard", "TDI"],
      "SQ8": ["Standard", "TDI"],
      "RSQ3": ["Sportback"],
      "RSQ8": ["Standard", "Performance"],
      "Q4 e-tron": ["40", "45", "50", "Sportback"],
      "Q6 e-tron": ["Performance", "Quattro", "SQ6"],
      "Q8 e-tron": ["50", "55", "SQ8", "Sportback"],
      "e-tron GT": ["Standard", "S", "RS", "RS Performance"],
      "A1": ["Sportback", "Citycarver", "S1"],
      "A2": ["Standard"],
      "100": ["C1", "C2", "C3", "C4"],
      "200": ["20V", "Avant"],
      "80": ["Standard", "S2", "RS2"],
      "Coupe": ["Quattro", "S2", "Sport"],
      "URquattro": ["Standard", "Sport", "20V"],
      "Allroad": ["A4", "A6"],
      "Other": ["Specify in title/description"]
    },
    "Avatr": {
      "11": ["Standard Range", "Long Range", "Performance"],
      "12": ["Standard", "Long Range"],
      "Other": ["Specify in title/description"]
    },
    "Bentley": {
      "Continental GT": ["V8", "W12", "Speed", "Mulliner", "Azure"],
      "Continental GTC": ["V8", "W12", "Speed", "Mulliner", "Azure"],
      "Flying Spur": ["V6", "V8", "W12", "Speed", "Mulliner", "Azure"],
      "Bentayga": ["V8", "Hybrid", "Speed", "Azure", "EWB"],
      "Mulsanne": ["Standard", "Speed", "Mulliner", "WO Edition"],
      "Arnage": ["R", "T", "Final Series"],
      "Brooklands": ["Coupe"],
      "Azure": ["Standard", "Mulliner"],
      "Continental GT3-R": ["Standard"],
      "Bentayga EWB": ["Standard", "Mulliner", "Azure"],
      "Batur": ["Coupe", "Convertible"],
      "Other": ["Specify in title/description"]
    },
    "BMW": {
      "1 Series": ["116i", "118i", "120i", "M135i"],
      "2 Series": ["218i", "220i", "230i", "M235i", "M240i", "M2"],
      "3 Series": ["318i", "320i", "330i", "340i", "M340i", "M3"],
      "4 Series": ["420i", "430i", "440i", "M440i", "M4"],
      "5 Series": ["520i", "523i", "525i", "528i", "530i", "535i", "540i", "550i", "M550i", "M5"],
      "6 Series": ["630i", "640i", "650i", "M6"],
      "7 Series": ["730i", "740i", "745e", "750i", "760i", "M760i"],
      "8 Series": ["840i", "850i", "M850i", "M8"],
      "X1": ["sDrive18i", "sDrive20i", "xDrive20i", "xDrive28i", "M35i"],
      "X2": ["sDrive18i", "sDrive20i", "xDrive20i", "M35i"],
      "X3": ["sDrive20i", "xDrive20i", "xDrive30i", "xDrive30e", "M40i", "M Competition"],
      "X4": ["xDrive20i", "xDrive30i", "M40i", "M Competition"],
      "X5": ["xDrive25d", "xDrive40i", "xDrive50i", "xDrive45e", "M50i", "M Competition"],
      "X6": ["xDrive40i", "xDrive50i", "M50i", "M Competition"],
      "X7": ["xDrive40i", "xDrive50i", "M60i", "Alpina XB7"],
      "XM": ["Standard", "Label", "Label Red"],
      "Z4": ["sDrive20i", "sDrive30i", "M40i"],
      "iX": ["xDrive40", "xDrive50", "M60"],
      "i4": ["eDrive35", "eDrive40", "M50"],
      "i7": ["xDrive60", "M70"],
      "i5": ["eDrive40", "M60"],
      "M2": ["Coupe", "CS", "Competition", "CSL"],
      "M3": ["Sedan", "Touring", "CS", "Competition", "CSL"],
      "M4": ["Coupe", "Convertible", "CS", "CSL", "Competition"],
      "M5": ["Sedan", "Touring", "CS", "Competition"],
      "M6": ["Coupe", "Convertible", "Gran Coupe", "CS", "Competition"],
      "M8": ["Coupe", "Convertible", "Gran Coupe", "Competition", "CS"],
      "X3 M": ["Standard", "Competition"],
      "X4 M": ["Standard", "Competition"],
      "X5 M": ["Standard", "Competition", "50e"],
      "X6 M": ["Standard", "Competition"],
      "Z3": ["Roadster", "Coupe", "M Roadster", "M Coupe"],
      "Z8": ["Standard"],
      "8 Series Gran Coupe": ["840i", "850i", "M850i", "M8"],
      "i3": ["Standard", "Range Extender", "S"],
      "i8": ["Coupe", "Roadster"],
      "iX1": ["xDrive30", "eDrive20", "M Sport"],
      "iX2": ["eDrive20", "xDrive30", "M35"],
      "iX3": ["M Sport", "Standard", "M50"],
      "i5 Touring": ["eDrive40", "M60"],
      "Other": ["Specify in title/description"]
    },
    "BYD": {
      "Atto 3": ["Standard Range", "Extended Range"],
      "Han": ["EV", "DM"],
      "Tang": ["EV", "DM"],
      "Seal": ["Standard", "Performance"],
      "Dolphin": ["Standard", "Extended Range"],
      "Seagull": ["Standard"],
      "Song Plus": ["EV", "DM"],
      "Song Pro": ["EV", "DM"],
      "Yuan Plus": ["Standard", "Long Range"],
      "Other": ["Specify in title/description"]
    },
    "Cadillac": {
      "CT4": ["Luxury", "Premium Luxury", "Sport", "V-Series Blackwing", "V", "V Blackwing"],
      "CT5": ["Luxury", "Premium Luxury", "Sport", "V-Series Blackwing", "V", "V Blackwing"],
      "Escalade": ["Luxury", "Premium Luxury", "Sport", "Platinum", "ESV Luxury", "ESV Platinum", "Sport Platinum", "V-Series"],
      "XT4": ["Luxury", "Premium Luxury", "Sport"],
      "XT5": ["Luxury", "Premium Luxury", "Sport", "Platinum"],
      "XT6": ["Luxury", "Premium Luxury", "Sport", "Platinum"],
      "LYRIQ": ["Luxury", "Sport", "Platinum"],
      "Escalade ESV": ["Luxury", "Premium Luxury", "Sport", "V-Series"],
      "Escalade EXT": ["Luxury", "Premium"],
      "Escalade IQ": ["Luxury", "Sport"],
      "CT6": ["Luxury", "Premium Luxury", "Sport", "Platinum", "CT6-V"],
      "CTS": ["Luxury", "Premium Luxury", "V-Sport", "CTS-V"],
      "ATS": ["Luxury", "Premium", "Performance", "ATS-V"],
      "STS": ["V6", "V8", "V"],
      "DTS": ["Luxury", "Premium", "Platinum"],
      "XLR": ["Standard", "V"],
      "ELR": ["Standard"],
      "Lyriq": ["Luxury", "Sport", "V"],
      "Celestiq": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Changan": {
      "Alsvin": ["Standard", "Comfort", "Luxury"],
      "CS35 Plus": ["Standard", "Luxury"],
      "CS55 Plus": ["Standard", "Luxury", "Elite"],
      "CS75 Plus": ["Standard", "Luxury", "Elite"],
      "CS85": ["Standard", "Luxury"],
      "Uni-K": ["Standard", "Luxury"],
      "Uni-T": ["Standard", "Luxury"],
      "Uni-V": ["Standard", "Luxury"],
      "Hunter": ["Standard", "Luxury"],
      "Other": ["Specify in title/description"]
    },
    "Chery": {
      "Tiggo 4 Pro": ["Standard", "Luxury"],
      "Tiggo 7 Pro": ["Standard", "Luxury", "Elite"],
      "Tiggo 8 Pro": ["Standard", "Luxury", "Elite"],
      "Arrizo 5": ["Standard", "Luxury"],
      "Arrizo 6 Pro": ["Standard", "Luxury"],
      "Omoda 5": ["Standard", "Luxury"],
      "Jaecoo 7": ["Standard", "Luxury"],
      "Jaecoo 8": ["Standard", "Luxury"],
      "Other": ["Specify in title/description"]
    },
    "Chevrolet": {
      "Camaro": ["LS", "LT", "LT1", "SS", "ZL1", "ZL1 1LE"],
      "Corvette": ["Stingray", "Z06", "E-Ray", "ZR1"],
      "Silverado": ["WT", "Custom", "LT", "RST", "LTZ", "High Country"],
      "Tahoe": ["LS", "LT", "RST", "Z71", "Premier", "High Country"],
      "Suburban": ["LS", "LT", "RST", "Z71", "Premier", "High Country"],
      "Traverse": ["LS", "LT", "RS", "Premier", "High Country"],
      "Trailblazer": ["LS", "LT", "RS", "ACTIV"],
      "Equinox": ["LS", "LT", "RS", "Premier"],
      "Malibu": ["LS", "LT", "RS", "Premier"],
      "Captiva": ["Standard", "LS", "LT", "Premier"],
      "Blazer": ["LT", "RS", "SS"],
      "Colorado": ["WT", "LT", "Z71", "ZR2", "Trail Boss"],
      "Impala": ["LS", "LT", "Premier", "SS"],
      "Cruze": ["LS", "LT", "LTZ", "Premier", "Hatch"],
      "Spark": ["LS", "LT", "LTZ", "ACTIV", "EV"],
      "Sonic": ["LS", "LT", "LTZ", "RS"],
      "Aveo": ["LS", "LT", "Ultra"],
      "Bolt": ["EV", "EUV", "Premier"],
      "SS": ["Performance"],
      "Caprice": ["Classic", "PPV"],
      "Astro": ["Cargo", "Passenger", "AWD"],
      "Express": ["Cargo", "Passenger", "Cutaway"],
      "Avalanche": ["LS", "LT", "LTZ", "Z71"],
      "TrailBlazer 2002": ["LS", "LT", "LTZ", "SS"],
      "Colorado ZR2": ["Standard", "Bison", "Off-Road"],
      "Silverado HD": ["2500 LT", "2500 LTZ", "2500 High Country", "3500 LT", "3500 LTZ", "3500 High Country", "ZR2"],
      "Silverado EV": ["Work Truck", "RST"],
      "Corvette Z06": ["Standard", "Z07", "E-Ray"],
      "Corvette ZR1": ["Standard", "ZTK"],
      "Stingray": ["Standard", "Convertible", "Z51"],
      "Camaro ZL1": ["Standard", "1LE"],
      "Camaro SS": ["1SS", "2SS", "1LE"],
      "Other": ["Specify in title/description"]
    },
    "Chrysler": {
      "300": ["Touring", "300S", "300C", "SRT8"],
      "Pacifica": ["Touring", "Touring L", "Touring L Plus", "Limited", "Pinnacle", "Hybrid"],
      "Other": ["Specify in title/description"]
    },
    "Citro\u00ebn": {
      "C3": ["Feel", "Shine", "C-Series"],
      "C4": ["Feel", "Shine", "C-Series"],
      "C5 X": ["Feel", "Shine", "C-Series"],
      "Berlingo": ["Feel", "Shine"],
      "Other": ["Specify in title/description"]
    },
    "Dacia": {
      "Sandero": ["Access", "Essential", "Expression", "Extreme"],
      "Duster": ["Essential", "Expression", "Extreme"],
      "Jogger": ["Essential", "Expression", "Extreme"],
      "Other": ["Specify in title/description"]
    },
    "Dodge": {
      "Charger": ["SXT", "GT", "R/T", "Scat Pack", "SRT Hellcat", "SRT Hellcat Redeye", "SRT Super Stock"],
      "Challenger": ["SXT", "GT", "R/T", "Scat Pack", "SRT Hellcat", "SRT Hellcat Redeye", "SRT Super Stock", "SRT Demon"],
      "Durango": ["SXT", "GT", "Citadel", "R/T", "SRT 392", "SRT Hellcat"],
      "RAM 1500": ["Tradesman", "Big Horn", "Rebel", "Laramie", "Longhorn", "Limited", "TRX"],
      "RAM 2500": ["Tradesman", "Big Horn", "Laramie", "Longhorn", "Limited", "Power Wagon"],
      "RAM 3500": ["Tradesman", "Big Horn", "Laramie", "Longhorn", "Limited"],
      "Other": ["Specify in title/description"]
    },
    "Ferrari": {
      "Roma": ["Standard", "Spider"],
      "Portofino": ["Standard", "M"],
      "SF90": ["Stradale", "Spider", "XX", "XX Spider"],
      "296": ["GTB", "GTS", "XX", "XX Spider"],
      "F8": ["Tributo", "Spider"],
      "812": ["Superfast", "GTS", "Competizione", "Competizione A"],
      "Purosangue": ["Standard"],
      "GTC4Lusso": ["Standard", "T"],
      "488": ["GTB", "Spider", "Pista", "Pista Spider"],
      "458": ["Italia", "Spider", "Speciale", "Speciale A"],
      "LaFerrari": ["Coupe", "Aperta"],
      "Enzo": ["Standard"],
      "F40": ["Standard", "LM"],
      "F50": ["Standard"],
      "F12": ["Berlinetta", "TDF"],
      "FF": ["Standard"],
      "California": ["Standard", "T", "T Handling Speciale"],
      "California T": ["Standard", "Handling Speciale"],
      "599": ["GTB Fiorano", "GTO", "SA Aperta"],
      "612": ["Scaglietti", "Sessanta"],
      "Mondial": ["8", "Quattrovalvole", "T", "T Cabriolet"],
      "360": ["Modena", "Spider", "Challenge Stradale"],
      "F430": ["Berlinetta", "Spider", "Scuderia", "16M"],
      "550": ["Maranello", "Barchetta"],
      "575M": ["Maranello", "Superamerica"],
      "Testarossa": ["Standard", "512 TR", "F512 M"],
      "Daytona": ["365 GTB/4", "365 GTS/4"],
      "Daytona SP3": ["Standard"],
      "Monza": ["SP1", "SP2"],
      "456": ["GT", "GTA", "M GT", "M GTA"],
      "348": ["TB", "TS", "Spider", "Challenge"],
      "F355": ["Berlinetta", "GTS", "Spider", "F1"],
      "Other": ["Specify in title/description"]
    },
    "Fiat": {
      "500": ["Pop", "Sport", "Lounge", "Abarth", "500e"],
      "Tipo": ["Easy", "Lounge", "Sport"],
      "Panda": ["Easy", "City Cross", "Cross"],
      "Doblo": ["Standard", "Cargo"],
      "Other": ["Specify in title/description"]
    },
    "Ford": {
      "Mustang": ["EcoBoost", "GT", "Mach 1", "Shelby GT350", "Shelby GT500", "Dark Horse"],
      "F-150": ["XL", "XLT", "Lariat", "King Ranch", "Platinum", "Limited", "Raptor", "Raptor R"],
      "Explorer": ["Base", "XLT", "ST", "Platinum", "King Ranch", "Timberline"],
      "Bronco": ["Base", "Big Bend", "Black Diamond", "Outer Banks", "Badlands", "Wildtrak", "Raptor", "Heritage"],
      "Edge": ["SE", "SEL", "ST-Line", "Titanium", "ST"],
      "Escape": ["S", "SE", "SE Sport", "SEL", "Titanium", "PHEV"],
      "Ranger": ["XL", "XLT", "Lariat", "Raptor"],
      "Expedition": ["XL", "XLT", "Limited", "King Ranch", "Platinum", "Timberline"],
      "EcoSport": ["S", "SE", "SES", "Titanium"],
      "Puma": ["Titanium", "ST-Line", "ST"],
      "Kuga": ["Titanium", "ST-Line", "Vignale", "PHEV"],
      "GT": ["2005-06", "2017", "Heritage", "Carbon Series", "LM Edition", "Mk IV"],
      "Mustang Mach-E": ["Select", "Premium", "California Route 1", "GT", "GT Performance", "Rally"],
      "Lightning": ["Pro", "XLT", "Lariat", "Platinum"],
      "Maverick": ["XL", "XLT", "Lariat", "Tremor", "Hybrid"],
      "Crown Victoria": ["LX", "Sport", "Police Interceptor"],
      "Galaxy": ["Zetec", "Titanium"],
      "S-Max": ["Zetec", "Titanium", "ST-Line"],
      "Focus": ["Zetec", "Titanium", "ST", "ST-Line", "RS", "Electric"],
      "Fiesta": ["Zetec", "Titanium", "ST", "ST-Line", "Active"],
      "Fusion": ["S", "SE", "Titanium", "Sport", "Hybrid", "Energi"],
      "Taurus": ["SE", "SEL", "Limited", "SHO"],
      "Flex": ["SE", "SEL", "Limited"],
      "Five Hundred": ["SE", "SEL", "Limited"],
      "Tourneo": ["Custom", "Connect", "Courier"],
      "Transit": ["Cargo", "Crew", "Passenger", "Connect", "Custom"],
      "Territory": ["Trend", "Titanium", "ST-Line"],
      "Everest": ["Ambiente", "Trend", "Sport", "Titanium", "Platinum"],
      "F-250": ["XL", "XLT", "Lariat", "King Ranch", "Platinum", "Limited", "Tremor"],
      "F-350": ["XL", "XLT", "Lariat", "King Ranch", "Platinum", "Limited"],
      "Raptor": ["F-150", "R", "Bronco"],
      "Shelby GT350": ["Standard", "R"],
      "Shelby GT500": ["Standard", "Carbon Fiber Track Pack", "Heritage Edition"],
      "Other": ["Specify in title/description"]
    },
    "GAC": {
      "GS3": ["Standard", "Luxury"],
      "GS4": ["Standard", "Luxury", "Elite"],
      "GS5": ["Standard", "Luxury"],
      "GS8": ["Standard", "Luxury", "Elite"],
      "Emkoo": ["Standard", "Luxury"],
      "Empow": ["Standard", "Luxury"],
      "Aion S": ["Standard", "Plus"],
      "Aion Y": ["Standard", "Plus"],
      "Other": ["Specify in title/description"]
    },
    "Genesis": {
      "G70": ["2.0T Standard", "2.0T Sport", "3.5T Sport", "2.0T", "3.3T", "Sport", "Sport Prestige"],
      "G80": ["2.5T Standard", "2.5T Sport", "3.5T Sport", "Electrified", "2.5T", "3.5T", "Sport", "Sport Prestige"],
      "G90": ["3.5T Standard", "3.5T Sport", "3.5T e-AWD", "3.5T", "5.0 Ultimate", "E-Supercharger", "Long Wheelbase"],
      "GV70": ["2.5T Standard", "2.5T Sport", "3.5T Sport", "Electrified", "2.5T", "3.5T", "Sport"],
      "GV80": ["2.5T Standard", "2.5T Sport", "3.5T Sport", "2.5T", "3.5T", "Coupe", "Magma"],
      "GV60": ["Standard", "Advanced", "Performance", "Magma"],
      "X Convertible": ["Concept"],
      "Other": ["Specify in title/description"]
    },
    "GMC": {
      "Sierra 1500": ["Pro", "SLE", "Elevation", "SLT", "AT4", "Denali", "Denali Ultimate"],
      "Sierra 2500": ["Pro", "SLE", "SLT", "AT4", "Denali"],
      "Yukon": ["SLE", "SLT", "AT4", "Denali", "XL SLE", "XL SLT", "XL AT4", "XL Denali"],
      "Terrain": ["SLE", "SLT", "AT4", "Denali"],
      "Acadia": ["SLE", "SLT", "AT4", "Denali"],
      "Canyon": ["Elevation", "AT4", "Denali", "AT4X"],
      "Hummer EV": ["SUV", "Pickup", "2X", "3X", "Edition 1"],
      "Sierra HD": ["2500 SLE", "2500 SLT", "2500 AT4", "2500 Denali", "3500 Denali", "3500 AT4"],
      "Sierra EV": ["Pro", "Denali", "AT4"],
      "Sierra 3500": ["SLE", "SLT", "AT4", "Denali", "Dually"],
      "Yukon XL": ["SLE", "SLT", "AT4", "Denali", "Denali Ultimate"],
      "Savana": ["Cargo", "Passenger", "Cutaway"],
      "Envoy": ["SLE", "SLT", "Denali", "XL", "XUV"],
      "Jimmy": ["SL", "SLE", "SLT"],
      "Sonoma": ["SL", "SLS", "SLE"],
      "Syclone": ["Standard"],
      "Typhoon": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Haval": {
      "H2": ["Standard", "Luxury"],
      "H6": ["Standard", "Luxury", "Elite", "Ultra"],
      "H9": ["Standard", "Luxury", "Elite"],
      "Jolion": ["Standard", "Luxury", "Elite"],
      "Dargo": ["Standard", "Luxury"],
      "Big Dog": ["Standard", "Luxury"],
      "Other": ["Specify in title/description"]
    },
    "Honda": {
      "Civic": ["LX", "Sport", "EX", "EX-L", "Touring", "Si", "Type R"],
      "Accord": ["LX", "Sport", "EX-L", "Touring", "Hybrid", "Hybrid Sport", "Hybrid Touring"],
      "CR-V": ["LX", "EX", "EX-L", "Touring", "Hybrid", "Hybrid EX", "Hybrid EX-L", "Hybrid Touring"],
      "HR-V": ["LX", "Sport", "EX", "EX-L"],
      "Pilot": ["Sport", "EX-L", "TrailSport", "Touring", "Elite", "Black Edition"],
      "Passport": ["Sport", "EX-L", "TrailSport", "Touring", "Elite"],
      "Ridgeline": ["Sport", "RTL", "RTL-E", "Black Edition"],
      "Odyssey": ["LX", "EX", "EX-L", "Touring", "Elite"],
      "City": ["LX", "EX", "EX-L", "RS"],
      "Jazz": ["S", "V", "RS"],
      "BR-V": ["S", "V", "RS"],
      "WR-V": ["S", "V", "RS"],
      "ZR-V": ["LX", "EX", "Sport", "EX-L", "Touring"],
      "Prologue": ["EX", "EX-L", "Touring"],
      "Integra": ["Standard", "Type R", "DC2", "DC5"],
      "S2000": ["Standard", "CR", "Type S"],
      "NSX": ["Standard", "Type S", "Type R", "Targa"],
      "Prelude": ["Si", "VTi", "SiR", "Type S"],
      "Insight": ["EX", "LX", "Touring"],
      "Clarity": ["Plug-in Hybrid", "Fuel Cell", "Electric"],
      "Element": ["EX", "LX", "SC"],
      "CR-Z": ["Sport", "EX", "Mugen"],
      "Fit": ["LX", "EX", "Sport"],
      "Brio": ["Standard", "Amaze", "RS"],
      "Mobilio": ["Standard", "RS"],
      "BRV": ["S", "V", "Prestige"],
      "Stream": ["Standard", "Type S"],
      "Stepwgn": ["G", "Spada", "e:HEV"],
      "Freed": ["G", "Hybrid", "Crosstar"],
      "N-Box": ["Standard", "Custom"],
      "N-One": ["Premium", "RS"],
      "Vezel": ["Standard", "Hybrid", "e:HEV"],
      "Other": ["Specify in title/description"]
    },
    "Hyundai": {
      "Accent": ["GL", "GLS", "GS"],
      "Elantra": ["SE", "SEL", "N Line", "Limited", "N"],
      "Sonata": ["SE", "SEL", "N Line", "Limited", "Hybrid", "Hybrid Blue", "Hybrid SEL Premium"],
      "Tucson": ["SE", "SEL", "N Line", "XRT", "Limited", "Hybrid", "Hybrid Blue", "Hybrid SEL", "Hybrid Limited", "PHEV"],
      "Santa Fe": ["SE", "SEL", "XRT", "Limited", "Calligraphy", "Hybrid", "Hybrid SEL", "Hybrid Limited", "Hybrid Calligraphy", "PHEV"],
      "Palisade": ["SE", "SEL", "XRT", "Limited", "Calligraphy"],
      "Kona": ["SE", "SEL", "N Line", "Limited", "Electric", "Electric SEL", "Electric Limited"],
      "Venue": ["SE", "SEL", "Denim"],
      "Ioniq 5": ["Standard Range RWD", "Long Range RWD", "Long Range AWD", "N"],
      "Ioniq 6": ["Standard Range RWD", "Long Range RWD", "Long Range AWD"],
      "Ioniq 9": ["Standard", "Long Range", "Performance"],
      "Creta": ["GL", "GLS", "Prime"],
      "i10": ["GL", "GLS"],
      "i20": ["GL", "GLS", "N Line"],
      "i30": ["GL", "GLS", "N Line", "N"],
      "Staria": ["Standard", "Premium", "Lounge"],
      "Veloster": ["Standard", "Turbo", "N", "R-Spec"],
      "Genesis Coupe": ["2.0T", "3.8 R-Spec", "3.8 Ultimate"],
      "Genesis Sedan": ["3.8", "4.6", "5.0 R-Spec"],
      "Veracruz": ["GLS", "Limited"],
      "Equus": ["Signature", "Ultimate"],
      "Azera": ["GLS", "Limited"],
      "Atos": ["GL", "GLS", "Prime"],
      "Getz": ["GL", "GLS"],
      "i40": ["Comfort", "Style", "Premium"],
      "Bayon": ["Pure", "Comfort", "Premium"],
      "H1": ["Cargo", "Wagon", "Limousine"],
      "H100": ["Cargo", "Wagon", "Truck"],
      "Starex": ["GL", "CRDi", "Royale"],
      "Galloper": ["Standard"],
      "Terracan": ["Standard"],
      "Centennial": ["Standard"],
      "Excel": ["Standard", "GL", "GLS"],
      "Stellar": ["Standard", "CXL"],
      "Pony": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Infiniti": {
      "Q50": ["Pure", "Luxe", "Red Sport 400", "Sensory", "Red Sport", "Eau Rouge"],
      "Q60": ["Pure", "Luxe", "Red Sport 400", "Sensory", "Red Sport", "Project Black S"],
      "QX50": ["Pure", "Luxe", "Sensory", "Autograph"],
      "QX55": ["Pure", "Luxe", "Sensory", "Autograph", "Essential"],
      "QX60": ["Pure", "Luxe", "Sensory", "Autograph"],
      "QX80": ["Luxe", "Sensory", "Autograph", "Monograph", "Premium Select"],
      "Q70": ["3.7 Premium", "3.7 Sport", "5.6", "Hybrid"],
      "QX30": ["Premium", "Sport"],
      "QX70": ["3.7", "5.0 S", "S Limited"],
      "G35": ["Standard", "Sport", "X", "Coupe"],
      "G37": ["Journey", "Sport", "X", "IPL", "Convertible"],
      "M37": ["Standard", "Sport"],
      "M56": ["Standard", "Sport"],
      "FX35": ["Standard", "Sport", "Premium"],
      "FX45": ["Standard", "Premium"],
      "FX50": ["Standard", "Sport"],
      "Other": ["Specify in title/description"]
    },
    "Isuzu": {
      "D-Max": ["Standard", "LS", "V-Cross", "Hi-Lander"],
      "MU-X": ["Standard", "LS", "LS-A", "LS-T"],
      "Trooper": ["Standard", "LS"],
      "Other": ["Specify in title/description"]
    },
    "Jaguar": {
      "XE": ["SE", "R-Dynamic SE", "R-Dynamic HSE", "R-Dynamic S", "P200", "P250", "P300", "R-Dynamic"],
      "XF": ["SE", "R-Dynamic SE", "R-Dynamic HSE", "R-Dynamic S", "P250", "P300", "R-Dynamic", "P450"],
      "XJ": ["Premium Luxury", "Portfolio", "Autobiography", "R-Sport", "XJR575", "XJL Portfolio"],
      "F-Type": ["R-Dynamic", "R", "R 75", "SVR", "P300", "P380", "75", "Project 7"],
      "E-Pace": ["SE", "R-Dynamic SE", "R-Dynamic HSE", "R-Dynamic S", "S", "HSE", "R-Dynamic"],
      "F-Pace": ["SE", "R-Dynamic SE", "R-Dynamic HSE", "SVR", "S", "HSE", "R-Dynamic"],
      "I-Pace": ["SE", "HSE", "First Edition", "S", "Black"],
      "XK": ["Coupe", "Convertible", "XKR", "XKR-S"],
      "E-Type": ["Series 1", "Series 2", "Series 3", "Lightweight"],
      "XJS": ["Coupe", "Convertible", "XJR-S"],
      "XK8": ["Coupe", "Convertible"],
      "XKR": ["Coupe", "Convertible", "Final Edition"],
      "S-Type": ["3.0", "4.2", "R", "Diesel"],
      "X-Type": ["2.0", "2.5", "3.0", "Estate"],
      "Other": ["Specify in title/description"]
    },
    "Jeep": {
      "Wrangler": ["Sport", "Willys", "Freedom", "Sahara", "Rubicon", "392", "4xe"],
      "Gladiator": ["Sport", "Willys", "Freedom", "Overland", "Mojave", "Rubicon"],
      "Grand Cherokee": ["Laredo", "Altitude", "Limited", "Trailhawk", "Overland", "Summit", "Summit Reserve", "SRT", "Trackhawk", "4xe"],
      "Grand Cherokee L": ["Laredo", "Limited", "Overland", "Summit", "Summit Reserve"],
      "Cherokee": ["Sport", "Latitude", "Latitude Plus", "Trailhawk", "Limited", "Overland"],
      "Compass": ["Sport", "Latitude", "Latitude Lux", "Trailhawk", "Limited", "High Altitude"],
      "Renegade": ["Sport", "Latitude", "Trailhawk", "Limited", "High Altitude"],
      "Other": ["Specify in title/description"]
    },
    "Jetour": {
      "X70": ["Standard", "Luxury"],
      "X70 Plus": ["Standard", "Luxury"],
      "X90": ["Standard", "Luxury"],
      "X90 Plus": ["Standard", "Luxury"],
      "Dashing": ["Standard", "Luxury"],
      "T2": ["Standard", "Luxury"],
      "Other": ["Specify in title/description"]
    },
    "Kia": {
      "Picanto": ["LX", "EX", "GT-Line"],
      "Rio": ["LX", "EX", "GT-Line", "S"],
      "Cerato": ["LX", "EX", "GT-Line", "GT"],
      "Stinger": ["GT-Line", "GT1", "GT2"],
      "Sportage": ["LX", "EX", "EX Premium", "GT-Line", "GT-Line Premium", "X-Line", "SX", "SX Prestige", "X-Pro"],
      "Tucson": ["LX", "EX", "GT-Line"],
      "Sorento": ["LX", "S", "EX", "SX", "SX Prestige", "X-Line", "Hybrid", "Hybrid EX", "Hybrid SX", "Hybrid SX Prestige", "PHEV"],
      "Telluride": ["LX", "S", "EX", "SX", "SX-P", "X-Line", "X-Pro"],
      "Carnival": ["LX", "EX", "SX", "SX Prestige"],
      "EV6": ["Light", "Wind", "GT-Line", "GT"],
      "EV9": ["Light", "Wind", "GT-Line"],
      "Niro": ["LX", "EX", "EX Premium", "Touring", "EV LX", "EV EX", "EV EX Premium", "EV Wind", "EV GT-Line"],
      "Soul": ["LX", "S", "EX", "GT-Line", "EV"],
      "Mohave": ["LX", "EX", "Gravity"],
      "K5": ["LX", "GT-Line", "EX", "GT"],
      "K8": ["Standard", "Luxury", "Prestige"],
      "K9": ["Standard", "Luxury", "Prestige"],
      "Optima": ["LX", "EX", "SX", "SXL", "Hybrid"],
      "Forte": ["LX", "S", "EX", "GT"],
      "Cadenza": ["Premium", "Technology", "SXL"],
      "K900": ["Luxury", "Premium"],
      "Seltos": ["LX", "EX", "S", "SX", "X-Line"],
      "Soul EV": ["S", "EX", "GT-Line"],
      "Pegas": ["Standard", "Comfort"],
      "Soluto": ["LX", "EX"],
      "Pride": ["Standard", "Hatchback"],
      "Spectra": ["Standard", "LX", "EX"],
      "Sephia": ["Standard", "LS"],
      "Sedona": ["LX", "EX", "SX", "SX Limited"],
      "Borrego": ["LX", "EX", "Limited"],
      "Other": ["Specify in title/description"]
    },
    "Lamborghini": {
      "Huracan": ["EVO", "EVO RWD", "STO", "Tecnica", "Sterrato"],
      "Urus": ["Standard", "S", "Performante"],
      "Revuelto": ["Standard", "Opera Unica"],
      "Countach": ["LPI 800-4"],
      "Aventador": ["LP700-4", "LP720-4", "SV", "SVJ", "Ultimae", "S", "S Roadster", "SVJ Roadster"],
      "Gallardo": ["LP500", "LP520", "LP560-4", "LP570-4", "Superleggera", "Spyder", "Bicolore", "Squadra Corse"],
      "Murcielago": ["6.2", "LP640", "LP670 SV", "Roadster", "SV Roadster"],
      "Diablo": ["VT", "SE30", "SV", "6.0", "GT", "VT Roadster"],
      "Reventon": ["Coupe", "Roadster"],
      "Veneno": ["Coupe", "Roadster"],
      "Centenario": ["Coupe", "Roadster"],
      "Sian": ["FKP 37", "Roadster"],
      "Asterion": ["Concept"],
      "Estoque": ["Concept"],
      "Egoista": ["Concept"],
      "Jalpa": ["P350"],
      "Silhouette": ["P300"],
      "Espada": ["Series I", "Series II", "Series III"],
      "Miura": ["P400", "P400 S", "P400 SV", "SVJ"],
      "Islero": ["S"],
      "350 GT": ["Coupe", "Spider"],
      "400 GT": ["2+2"],
      "LM002": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Land Rover": {
      "Defender": ["90 S", "90 SE", "90 HSE", "90 X", "90 V8", "110 S", "110 SE", "110 HSE", "110 X", "110 V8", "130 SE", "130 HSE", "130 X"],
      "Discovery": ["S", "SE", "HSE", "R-Dynamic SE", "R-Dynamic HSE", "Metropolitan Edition"],
      "Discovery Sport": ["S", "SE", "R-Dynamic SE", "R-Dynamic HSE", "R-Dynamic S"],
      "Range Rover": ["SE", "HSE", "Autobiography", "SV", "SV Autobiography", "PHEV SE", "PHEV HSE", "PHEV Autobiography"],
      "Range Rover Sport": ["SE", "Dynamic SE", "Dynamic HSE", "Autobiography Dynamic", "SVR", "PHEV SE", "PHEV Dynamic SE"],
      "Range Rover Velar": ["S", "SE", "R-Dynamic SE", "R-Dynamic HSE", "SV Autobiography Dynamic"],
      "Range Rover Evoque": ["S", "SE", "R-Dynamic SE", "R-Dynamic HSE", "Autobiography"],
      "Defender 2020": ["90", "110", "130", "Hard Top"],
      "Defender Classic": ["90", "110", "130", "Heritage Edition"],
      "Series I": ["80", "86", "88", "107"],
      "Series II": ["88", "109"],
      "Series III": ["88", "109", "Stage 1"],
      "Range Rover Classic": ["3-Door", "4-Door", "CSK", "Vogue"],
      "Range Rover P38": ["HSE", "Vogue", "Autobiography"],
      "Range Rover L322": ["HSE", "Vogue", "Supercharged", "Autobiography"],
      "Freelander": ["1", "2", "HSE", "Sport"],
      "LR2": ["Base", "HSE", "HSE LUX"],
      "LR3": ["Base", "HSE", "SE"],
      "LR4": ["Base", "HSE", "LUX", "HSE LUX"],
      "Other": ["Specify in title/description"]
    },
    "Lexus": {
      "CT": ["200h", "200h F Sport", "F Sport"],
      "ES": ["250", "300h", "350", "350 F Sport"],
      "GS": ["200t", "300", "350", "450h", "F Sport"],
      "GX": ["460", "460 Premium", "460 Luxury", "550", "550 Premium Plus", "550 Overtrail+"],
      "IS": ["200t", "300", "300 F Sport", "350", "350 F Sport", "500", "500 F Sport"],
      "LC": ["500", "500h", "500 Inspiration"],
      "LS": ["350", "500", "500h", "500 F Sport"],
      "LX": ["450d", "500d", "600", "600 F Sport", "600 Ultra Luxury"],
      "NX": ["200t", "250", "300h", "350", "350h", "350 F Sport", "450h+"],
      "RC": ["200t", "300", "350", "F"],
      "RX": ["300", "350", "350h", "450h", "450h+", "500h F Sport"],
      "UX": ["200", "250h", "300e"],
      "SC": ["300", "400", "430"],
      "HS": ["250h"],
      "GS F": ["Standard"],
      "IS F": ["Standard"],
      "LFA": ["Standard", "Nurburgring"],
      "RX L": ["350", "450h"],
      "LBX": ["Active", "Elegant", "Cool", "Relax"],
      "LM": ["350h", "500h"],
      "Other": ["Specify in title/description"]
    },
    "Lincoln": {
      "Aviator": ["Standard", "Reserve", "Black Label", "Grand Touring"],
      "Corsair": ["Standard", "Reserve", "Grand Touring"],
      "Navigator": ["Standard", "Reserve", "Black Label", "L Standard", "L Reserve", "L Black Label"],
      "Nautilus": ["Standard", "Reserve", "Black Label"],
      "Other": ["Specify in title/description"]
    },
    "Lucid": {
      "Air": ["Pure", "Touring", "Grand Touring", "Dream Edition", "Sapphire"],
      "Gravity": ["Standard", "Grand Touring"],
      "Other": ["Specify in title/description"]
    },
    "Maserati": {
      "Ghibli": ["GT", "Modena", "Trofeo"],
      "GranTurismo": ["Modena", "Trofeo", "Folgore"],
      "Grecale": ["GT", "Modena", "Trofeo", "Folgore"],
      "Levante": ["GT", "Modena", "Trofeo"],
      "MC20": ["Standard", "Cielo"],
      "Quattroporte": ["GT", "Modena", "Trofeo"],
      "GranTurismo MC": ["Stradale", "Sport"],
      "GranCabrio": ["Standard", "Sport", "MC", "Trofeo", "Folgore"],
      "3200 GT": ["Standard", "Assetto Corsa"],
      "Coupe": ["GT", "Cambiocorsa"],
      "Spyder": ["GT", "Cambiocorsa", "90th Anniversary"],
      "Biturbo": ["Coupe", "Spyder", "430"],
      "Bora": ["Standard"],
      "Khamsin": ["Standard"],
      "Merak": ["SS"],
      "Other": ["Specify in title/description"]
    },
    "Mazda": {
      "Mazda2": ["GL", "GS", "GT"],
      "Mazda3": ["GX", "GS", "GT", "Turbo"],
      "Mazda6": ["GX", "GS", "GT", "Signature"],
      "CX-3": ["GX", "GS", "GT"],
      "CX-30": ["GX", "GS", "GT", "Turbo"],
      "CX-5": ["GX", "GS", "GT", "Signature", "Carbon Edition", "Turbo"],
      "CX-50": ["GX", "GS", "GT", "Meridian Edition", "Turbo"],
      "CX-60": ["GX", "GS", "GT", "Signature", "PHEV"],
      "CX-90": ["GX", "GS", "GT", "Signature", "PHEV", "Turbo S"],
      "MX-5 Miata": ["Sport", "Club", "Grand Touring", "RF Club", "RF Grand Touring"],
      "MX-30": ["Standard", "R-EV"],
      "Other": ["Specify in title/description"]
    },
    "McLaren": {
      "Artura": ["Standard", "Performance", "Spider"],
      "720S": ["Standard", "Performance", "Spider", "Le Mans"],
      "750S": ["Coupe", "Spider"],
      "765LT": ["Coupe", "Spider"],
      "GT": ["Standard"],
      "Senna": ["Standard", "GTR"],
      "Elva": ["Standard"],
      "Speedtail": ["Standard"],
      "P1": ["Standard", "GTR", "LM"],
      "F1": ["Standard", "LM", "GTR"],
      "MP4-12C": ["Coupe", "Spider"],
      "650S": ["Coupe", "Spider", "Le Mans", "Sprint"],
      "675LT": ["Coupe", "Spider"],
      "570S": ["Coupe", "Spider"],
      "570GT": ["Standard", "Sport"],
      "540C": ["Coupe"],
      "600LT": ["Coupe", "Spider"],
      "Sabre": ["Standard"],
      "Solus GT": ["Standard"],
      "W1": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Mercedes-Benz": {
      "A-Class": ["A 180", "A 200", "A 220", "A 250", "A 35 AMG", "A 45 AMG", "A 45 S AMG"],
      "B-Class": ["B 180", "B 200", "B 220", "B 250 e"],
      "C-Class": ["C 180", "C 200", "C 220d", "C 300", "C 300 e", "C 43 AMG", "C 63 AMG", "C 63 S AMG", "C 63 S e Performance"],
      "E-Class": ["E 200", "E 220d", "E 300", "E 350", "E 400", "E 450", "E 53 AMG", "E 63 AMG", "E 63 S AMG"],
      "S-Class": ["S 400d", "S 450", "S 500", "S 580", "S 63 AMG", "S 680", "Maybach S 580", "Maybach S 650", "Maybach S 680"],
      "CLA": ["CLA 180", "CLA 200", "CLA 220", "CLA 250", "CLA 35 AMG", "CLA 45 AMG", "CLA 45 S AMG"],
      "CLS": ["CLS 300d", "CLS 450", "CLS 53 AMG"],
      "GLA": ["GLA 200", "GLA 220d", "GLA 250", "GLA 35 AMG", "GLA 45 AMG", "GLA 45 S AMG"],
      "GLB": ["GLB 200", "GLB 220d", "GLB 250", "GLB 35 AMG"],
      "GLC": ["GLC 200", "GLC 220d", "GLC 300", "GLC 300 e", "GLC 43 AMG", "GLC 63 AMG", "GLC 63 S AMG"],
      "GLE": ["GLE 300d", "GLE 350", "GLE 400d", "GLE 450", "GLE 580", "GLE 53 AMG", "GLE 63 AMG", "GLE 63 S AMG"],
      "GLS": ["GLS 450", "GLS 580", "GLS 63 AMG", "Maybach GLS 600", "Maybach GLS 680"],
      "G-Class": ["G 400d", "G 500", "G 63 AMG", "G 63 AMG Edition 1", "G 63 AMG Stronger Than Time", "G 63 AMG Manufaktur"],
      "AMG GT": ["AMG GT 43", "AMG GT 53", "AMG GT 63", "AMG GT 63 S", "AMG GT S", "AMG GT R", "AMG GT R Pro", "AMG GT Black Series"],
      "SL": ["SL 43", "SL 55", "SL 63", "SL 55 AMG", "SL 63 AMG"],
      "EQA": ["EQA 250", "EQA 300", "EQA 350"],
      "EQB": ["EQB 250", "EQB 300", "EQB 350"],
      "EQC": ["EQC 400"],
      "EQE": ["EQE 300", "EQE 350", "EQE 350+", "EQE 500", "AMG EQE 43", "AMG EQE 53"],
      "EQS": ["EQS 450+", "EQS 580", "AMG EQS 53", "Maybach EQS 680"],
      "EQV": ["EQV 300"],
      "C-Class Coupe": ["C200", "C300", "C43 AMG", "C63 AMG"],
      "C-Class Cabriolet": ["C200", "C300", "C43 AMG", "C63 AMG"],
      "E-Class Coupe": ["E200", "E300", "E450", "E53 AMG", "E63 AMG"],
      "E-Class Cabriolet": ["E200", "E300", "E450", "E53 AMG"],
      "E-Class All-Terrain": ["Standard"],
      "S-Class Coupe": ["S500", "S560", "S63 AMG", "S65 AMG"],
      "S-Class Cabriolet": ["S500", "S560", "S63 AMG", "S65 AMG"],
      "Maybach S-Class": ["S580", "S680", "Edition 100"],
      "Maybach GLS": ["600", "680"],
      "Maybach EQS SUV": ["680"],
      "CLK": ["200", "320", "430", "500", "55 AMG", "63 AMG", "DTM"],
      "CL": ["500", "600", "55 AMG", "63 AMG", "65 AMG"],
      "SLR McLaren": ["Coupe", "Roadster", "722", "Stirling Moss"],
      "SLS AMG": ["Coupe", "Roadster", "Black Series", "GT", "GT Final Edition"],
      "AMG GT R": ["Standard", "Pro", "Roadster", "Black Series"],
      "AMG GT 4-Door": ["43", "53", "63", "63 S", "63 S E Performance"],
      "AMG ONE": ["Standard"],
      "AMG SL": ["43", "55", "63", "63 S E Performance"],
      "GLA AMG": ["35", "45", "45 S"],
      "GLB AMG": ["35"],
      "GLC AMG": ["43", "63", "63 S Coupe"],
      "GLE AMG": ["53", "63 S", "53 Coupe", "63 S Coupe"],
      "GLS AMG": ["63"],
      "G63 AMG": ["Standard", "6x6", "4x4 Squared"],
      "G500": ["Standard", "4x4 Squared", "Cabriolet"],
      "G350d": ["Standard", "Professional"],
      "G350": ["Standard", "CDI"],
      "190E": ["Standard", "2.3-16", "2.5-16", "Evolution", "Evolution II"],
      "300SL": ["Gullwing", "Roadster"],
      "SLK": ["200", "230", "350", "55 AMG"],
      "SLC": ["180", "200", "300", "43 AMG"],
      "Citan": ["Tourer", "Crew Cab", "Panel Van"],
      "Vito": ["Tourer", "Mixto", "Panel Van"],
      "V-Class": ["Standard", "Marco Polo", "AMG Line"],
      "Sprinter": ["Cargo", "Crew", "Passenger"],
      "X-Class": ["Pure", "Progressive", "Power"],
      "Other": ["Specify in title/description"]
    },
    "MG": {
      "MG3": ["Standard", "Luxury"],
      "MG5": ["Standard", "Luxury", "EV Standard", "EV Luxury"],
      "MG6": ["Standard", "Luxury", "Trophy"],
      "MG ZS": ["Standard", "Luxury", "EV Standard", "EV Luxury", "EV Trophy"],
      "MG HS": ["Standard", "Luxury", "Trophy", "PHEV"],
      "MG RX5": ["Standard", "Luxury"],
      "MG RX8": ["Standard", "Luxury"],
      "MG4": ["Standard", "Luxury", "Trophy"],
      "MG7": ["Standard", "Luxury"],
      "Cyberster": ["Standard", "Trophy"],
      "Other": ["Specify in title/description"]
    },
    "Mini": {
      "Cooper": ["Classic", "Essential", "Resolute", "Iconic", "JCW", "S", "SE", "Convertible", "Clubman"],
      "Cooper S": ["Classic", "Essential", "Resolute", "Iconic", "JCW"],
      "Clubman": ["Cooper", "Cooper S", "Cooper ALL4", "Cooper S ALL4", "JCW ALL4", "JCW"],
      "Countryman": ["Cooper", "Cooper S", "Cooper SE ALL4", "Cooper S ALL4", "JCW ALL4", "JCW", "SE", "Plug-in Hybrid"],
      "Paceman": ["Cooper", "Cooper S", "Cooper ALL4", "Cooper S ALL4", "JCW"],
      "Convertible": ["Cooper", "Cooper S", "JCW"],
      "Coupe": ["Cooper", "Cooper S", "JCW"],
      "Roadster": ["Cooper", "Cooper S", "JCW"],
      "Electric": ["Standard", "Level 1", "Level 2", "Level 3"],
      "Aceman": ["E", "SE", "JCW"],
      "Other": ["Specify in title/description"]
    },
    "Mitsubishi": {
      "Eclipse Cross": ["GLX", "GLS", "Exceed", "PHEV"],
      "Outlander": ["GLX", "GLS", "Exceed", "PHEV"],
      "Pajero": ["GLX", "GLS", "Exceed"],
      "Pajero Sport": ["GLX", "GLS", "Exceed"],
      "ASX": ["GLX", "GLS", "Exceed"],
      "Galant": ["GLX", "GLS", "Exceed"],
      "Lancer": ["GLX", "GLS", "Evolution X"],
      "Lancer Evolution": ["EVO IV", "EVO V", "EVO VI", "EVO VII", "EVO VIII", "EVO IX", "EVO X", "Final Edition", "TME", "GSR", "RS", "MR"],
      "3000GT": ["SL", "VR-4", "Spyder"],
      "GTO": ["Standard", "Twin Turbo", "MR"],
      "FTO": ["GR", "GP", "GS", "Mivec"],
      "Galant VR-4": ["Standard"],
      "Eclipse": ["GS", "GST", "GSX", "Spyder", "Cross"],
      "Diamante": ["Standard", "ES", "LS", "VR-X"],
      "Sigma": ["Standard"],
      "Starion": ["ESI-R", "GSR-VR"],
      "i-MiEV": ["Standard", "Sport"],
      "Mirage": ["DE", "ES", "SE", "GT", "G4"],
      "Attrage": ["GLX", "GLS"],
      "Xpander": ["GLS", "Cross", "Sport"],
      "Triton": ["GL", "GLX", "GLS", "Premium", "Athlete"],
      "Montero": ["Standard", "Sport", "Limited"],
      "Other": ["Specify in title/description"]
    },
    "Nissan": {
      "Micra": ["Visia", "Acenta", "N-Sport", "Tekna"],
      "Sunny": ["S", "SV", "SL"],
      "Sentra": ["S", "SV", "SR", "SL"],
      "Altima": ["S", "SV", "SR", "SL", "Platinum", "VC-Turbo"],
      "Maxima": ["S", "SV", "SR", "SL", "Platinum"],
      "370Z": ["Sport", "Touring", "Nismo"],
      "GT-R": ["Premium", "Track Edition", "Nismo"],
      "Kicks": ["S", "SV", "SR", "Platinum"],
      "Juke": ["Visia", "Acenta", "N-Design", "Tekna", "Nismo"],
      "Qashqai": ["Visia", "Acenta", "N-Connecta", "Tekna", "Tekna+"],
      "X-Trail": ["S", "SV", "SL", "Platinum", "e-POWER"],
      "Murano": ["S", "SV", "SL", "Platinum"],
      "Pathfinder": ["S", "SV", "SL", "Platinum", "Rock Creek"],
      "Armada": ["S", "SV", "SL", "Platinum"],
      "Patrol": ["XE", "SE", "LE", "Platinum", "Nismo"],
      "Navara": ["XE", "SE", "LE", "Pro-4X"],
      "Frontier": ["S", "SV", "Pro-4X"],
      "Titan": ["S", "SV", "Pro-4X", "Platinum Reserve", "PRO-X"],
      "350Z": ["Base", "Touring", "Enthusiast", "Track", "NISMO", "Roadster"],
      "300ZX": ["Standard", "Turbo", "Twin Turbo", "Convertible"],
      "240SX": ["SE", "LE", "SE Convertible"],
      "Silvia": ["S13", "S14", "S15", "Spec R"],
      "Skyline": ["GT-R R32", "GT-R R33", "GT-R R34", "350GT", "370GT"],
      "Fairlady Z": ["Standard", "NISMO"],
      "Z": ["Sport", "Performance", "Heritage Edition", "NISMO"],
      "Cube": ["Standard", "Krom"],
      "Note": ["Standard", "e-Power", "Nismo"],
      "Leaf": ["S", "SV", "SL", "Plus"],
      "Ariya": ["Engage", "Venture+", "Evolve+", "Premiere", "Platinum+"],
      "Almera": ["Standard", "Visia", "Tekna"],
      "Tiida": ["Standard", "Latio"],
      "Versa": ["S", "SV", "SR"],
      "Sylphy": ["Standard", "CVT"],
      "Teana": ["Standard", "XV"],
      "Cefiro": ["Standard", "Excimo"],
      "Bluebird": ["Standard", "Sylphy"],
      "Primera": ["Standard", "P11", "P12"],
      "Caravan": ["DX", "GX", "Premium GX"],
      "Urvan": ["Standard", "Cargo", "Microbus"],
      "Civilian": ["Standard"],
      "Datsun": ["GO", "GO+", "redi-GO"],
      "President": ["Sovereign"],
      "Pulsar": ["Standard", "GTI-R"],
      "Other": ["Specify in title/description"]
    },
    "Peugeot": {
      "208": ["Active", "Allure", "GT", "e-208"],
      "308": ["Active", "Allure", "GT", "e-308"],
      "408": ["Allure", "GT"],
      "2008": ["Active", "Allure", "GT", "e-2008"],
      "3008": ["Active", "Allure", "GT", "GT Premium"],
      "5008": ["Active", "Allure", "GT"],
      "508": ["Allure", "GT", "SW"],
      "Other": ["Specify in title/description"]
    },
    "Porsche": {
      "911": ["Carrera", "Carrera S", "Carrera 4", "Carrera 4S", "Targa 4", "Targa 4S", "GT3", "GT3 RS", "GT3 Touring", "Turbo", "Turbo S", "Dakar", "Sport Classic"],
      "Cayenne": ["Base", "S", "E-Hybrid", "GTS", "Turbo", "Turbo S E-Hybrid", "Coupe Base", "Coupe S", "Coupe E-Hybrid", "Coupe GTS", "Coupe Turbo", "Coupe Turbo S E-Hybrid"],
      "Macan": ["Base", "S", "GTS", "Turbo", "Electric Base", "Electric 4", "Electric 4S", "Electric Turbo"],
      "Panamera": ["Base", "4", "4S", "GTS", "Turbo", "Turbo S", "Turbo S E-Hybrid", "Sport Turismo", "4 Sport Turismo"],
      "Taycan": ["Base", "4", "4S", "GTS", "Turbo", "Turbo S", "Cross Turismo", "4 Cross Turismo", "4S Cross Turismo", "GTS Sport Turismo", "Turbo Sport Turismo", "Turbo S Cross Turismo"],
      "718 Cayman": ["Base", "S", "GTS 4.0", "GT4", "GT4 RS", "Spyder", "Spyder RS"],
      "718 Boxster": ["Base", "S", "GTS 4.0", "Spyder"],
      "718 Spyder": ["Standard", "RS"],
      "Cayman": ["S", "GTS", "GT4", "GT4 RS"],
      "Boxster": ["S", "GTS", "Spyder"],
      "918": ["Spyder", "Spyder Weissach"],
      "Carrera GT": ["Standard"],
      "959": ["Standard"],
      "924": ["Standard", "Turbo", "S"],
      "928": ["Standard", "S", "S4", "GT", "GTS"],
      "944": ["Standard", "S", "S2", "Turbo"],
      "968": ["Standard", "Club Sport", "Turbo S"],
      "Macan EV": ["Standard", "4", "4S", "Turbo"],
      "Other": ["Specify in title/description"]
    },
    "RAM": {
      "1500": ["Tradesman", "Big Horn", "Laramie", "Rebel", "Limited", "TRX"],
      "2500": ["Tradesman", "Big Horn", "Laramie", "Power Wagon", "Limited"],
      "3500": ["Tradesman", "Big Horn", "Laramie", "Limited"],
      "Other": ["Specify in title/description"]
    },
    "Renault": {
      "Clio": ["Life", "Zen", "Intens", "RS Line", "E-Tech"],
      "Captur": ["Life", "Zen", "Intens", "RS Line", "E-Tech"],
      "Duster": ["Life", "Zen", "Intens", "4WD"],
      "Kadjar": ["Life", "Zen", "Intens"],
      "Koleos": ["Life", "Zen", "Intens", "Iconic"],
      "Megane": ["Life", "Zen", "Intens", "RS", "E-Tech"],
      "Arkana": ["Life", "Zen", "Intens", "RS Line"],
      "Austral": ["Life", "Zen", "Intens", "Iconic"],
      "Other": ["Specify in title/description"]
    },
    "Rolls-Royce": {
      "Ghost": ["Standard", "Extended", "Black Badge", "Prism"],
      "Phantom": ["Standard", "Extended", "EWB"],
      "Wraith": ["Standard", "Black Badge"],
      "Dawn": ["Standard", "Black Badge"],
      "Cullinan": ["Standard", "Black Badge", "Series II"],
      "Spectre": ["Standard"],
      "Silver Shadow": ["Standard", "Long Wheelbase"],
      "Silver Spirit": ["Standard"],
      "Silver Seraph": ["Standard", "Last of Line"],
      "Silver Cloud": ["I", "II", "III"],
      "Corniche": ["Coupe", "Convertible"],
      "Camargue": ["Standard"],
      "Park Ward": ["Standard"],
      "Boat Tail": ["Standard"],
      "La Rose Noire": ["Droptail"],
      "Amethyst": ["Droptail"],
      "Other": ["Specify in title/description"]
    },
    "Rox": {
      "T3": ["Standard", "Luxury"],
      "T5": ["Standard", "Luxury"],
      "T7": ["Standard", "Luxury"],
      "Other": ["Specify in title/description"]
    },
    "Skoda": {
      "Fabia": ["Active", "Ambition", "Style"],
      "Octavia": ["Active", "Ambition", "Style", "RS", "RS 245"],
      "Superb": ["Active", "Ambition", "Style", "Sportline"],
      "Kamiq": ["Active", "Ambition", "Style"],
      "Karoq": ["Active", "Ambition", "Style", "Sportline"],
      "Kodiaq": ["Active", "Ambition", "Style", "Sportline", "RS"],
      "Enyaq": ["50", "60", "80", "80x", "RS", "RS Coupe"],
      "Other": ["Specify in title/description"]
    },
    "Subaru": {
      "Impreza": ["Base", "Premium", "Sport", "Limited"],
      "Legacy": ["Base", "Premium", "Sport", "Limited", "Touring"],
      "Outback": ["Base", "Premium", "Sport", "Limited", "Touring", "Wilderness"],
      "Forester": ["Base", "Premium", "Sport", "Limited", "Touring", "Wilderness"],
      "Crosstrek": ["Base", "Premium", "Sport", "Limited", "Wilderness"],
      "Ascent": ["Base", "Premium", "Sport", "Limited", "Touring"],
      "WRX": ["Base", "Premium", "Sport", "Limited", "GT", "TR", "STI"],
      "BRZ": ["Base", "Premium", "Limited", "Series.Gray", "tS"],
      "Other": ["Specify in title/description"]
    },
    "Suzuki": {
      "Swift": ["GL", "GLX", "Sport"],
      "Baleno": ["GL", "GLX"],
      "Celerio": ["GL", "GLX"],
      "Dzire": ["GL", "GLX"],
      "Ertiga": ["GL", "GLX"],
      "Vitara": ["GL", "GLX", "Sport", "S-Cross"],
      "Grand Vitara": ["GL", "GLX", "Sport"],
      "Jimny": ["GL", "GLX", "Sierra"],
      "Fronx": ["GL", "GLX", "Alpha"],
      "Brezza": ["LXI", "VXI", "ZXI", "ZXI+"],
      "Other": ["Specify in title/description"]
    },
    "Tesla": {
      "Model 3": ["Standard Range", "Long Range", "Performance", "Highland Standard", "Highland Long Range", "Highland Performance", "Standard", "Highland"],
      "Model S": ["Long Range", "Plaid", "Plaid+", "60", "75", "85", "90D", "P100D"],
      "Model X": ["Long Range", "Plaid", "60D", "75D", "90D", "P100D"],
      "Model Y": ["Standard Range", "Long Range", "Performance", "Standard", "Juniper"],
      "Cybertruck": ["All-Wheel Drive", "Cyberbeast", "AWD", "Single Motor"],
      "Roadster (2008)": ["Sport", "2.5"],
      "Roadster (Next-gen)": ["Standard", "Founders Series", "SpaceX Package"],
      "Semi": ["300-mile", "500-mile"],
      "Other": ["Specify in title/description"]
    },
    "Toyota": {
      "Yaris": ["E", "G", "SE", "GR Sport", "GR"],
      "Corolla": ["E", "G", "SE", "XSE", "XLE", "Hybrid", "GR", "GR Sport"],
      "Camry": ["LE", "SE", "XSE", "XLE", "TRD", "Hybrid LE", "Hybrid SE", "Hybrid XSE", "Hybrid XLE"],
      "Avalon": ["XLE", "XSE", "Limited", "TRD", "Hybrid XLE", "Hybrid Limited"],
      "Prius": ["L Eco", "LE", "XLE", "Limited", "Prime LE", "Prime XSE", "Prime XSE Premium", "Prime Limited"],
      "C-HR": ["LE", "XLE", "Nightshade", "Limited"],
      "RAV4": ["LE", "XLE", "XLE Premium", "TRD Off-Road", "Adventure", "XSE Hybrid", "SE Hybrid", "XLE Hybrid", "XLE Premium Hybrid", "Limited Hybrid", "Prime SE", "Prime XSE", "Prime XSE Premium"],
      "Highlander": ["L", "LE", "XLE", "XSE", "Limited", "Platinum", "Hybrid LE", "Hybrid XLE", "Hybrid Limited", "Hybrid Platinum"],
      "4Runner": ["SR5", "TRD Sport", "TRD Off-Road", "TRD Off-Road Premium", "Limited", "Nightshade", "TRD Pro"],
      "Sequoia": ["SR5", "TRD Sport", "TRD Off-Road", "Limited", "Platinum", "Capstone", "TRD Pro", "Hybrid SR5", "Hybrid Limited", "Hybrid Platinum", "Hybrid Capstone", "Hybrid TRD Pro"],
      "Tundra": ["SR", "SR5", "Limited", "Platinum", "1794 Edition", "Capstone", "TRD Pro", "Hybrid SR5", "Hybrid Limited", "Hybrid Platinum", "Hybrid 1794", "Hybrid Capstone", "Hybrid TRD Pro"],
      "Land Cruiser": ["GX", "GX-R", "VX", "VX-R", "GR Sport", "300 GX", "300 VX", "300 GR Sport", "70 Series", "200 GX", "200 VX"],
      "Land Cruiser Prado": ["GX", "GX-R", "VX", "VX-R", "TXL"],
      "FJ Cruiser": ["Base", "Trail Teams"],
      "Fortuner": ["EXR", "VXR", "GR Sport"],
      "Hilux": ["E", "G", "SR", "SR5", "GR Sport"],
      "Tacoma": ["SR", "SR5", "TRD Sport", "TRD Off-Road", "Limited", "TRD Pro", "Trailhunter"],
      "Supra": ["2.0", "3.0", "3.0 Premium", "A91 Edition", "45th Anniversary"],
      "GR86": ["Base", "Premium"],
      "bZ4X": ["XLE", "Limited", "XLE AWD", "Limited AWD"],
      "Crown": ["XLE", "Limited", "Platinum", "Hybrid XLE", "Hybrid Limited", "Hybrid Platinum"],
      "Corolla Cross": ["LE", "SE", "XLE", "Hybrid"],
      "Yaris Cross": ["Standard", "Hybrid"],
      "Aygo": ["Standard", "X"],
      "Aurion": ["AT-X", "Sportivo", "Presara"],
      "Innova": ["G", "V", "Crysta", "Hycross"],
      "Rumion": ["Standard"],
      "Veloz": ["Standard"],
      "Raize": ["Standard", "Hybrid"],
      "Urban Cruiser": ["Standard", "Hybrid"],
      "Coaster": ["Standard", "High Roof", "23 Seater", "26 Seater", "30 Seater"],
      "Hiace": ["Cargo", "Commuter", "Standard Roof", "High Roof", "Super GL"],
      "Hilux Surf": ["SSR-X", "SSR-G"],
      "Crown Sport": ["Standard", "RS"],
      "Crown Signia": ["Standard", "Limited"],
      "Century": ["Sedan", "SUV"],
      "Sienna": ["LE", "XLE", "Limited", "Platinum"],
      "Mirai": ["XLE", "Limited"],
      "Venza": ["LE", "XLE", "Limited"],
      "Crown Athlete": ["Standard", "S", "G"],
      "Mark X": ["Standard", "GR Sport"],
      "Celica": ["GT", "GT-S", "All-Trac"],
      "MR2": ["Standard", "Spyder", "Turbo"],
      "Soarer": ["GT", "Aerocabin"],
      "Cresta": ["Standard", "Tourer V"],
      "Chaser": ["Standard", "Tourer V", "Avante"],
      "GR Yaris": ["Standard", "Performance", "Rallye"],
      "GR Corolla": ["Core", "Circuit", "Morizo"],
      "GR Supra": ["2.0", "3.0", "3.0 Premium", "A91", "MT"],
      "Other": ["Specify in title/description"]
    },
    "Volkswagen": {
      "Polo": ["Trendline", "Comfortline", "Highline", "GTI", "R-Line"],
      "Golf": ["Trendline", "Comfortline", "Highline", "GTI", "GTI Clubsport", "R", "R-Line", "S", "SE", "SEL", "Alltrack", "Sportwagen"],
      "Jetta": ["Trendline", "Comfortline", "Highline", "GLI", "S", "SE", "SEL", "R-Line"],
      "Passat": ["Trendline", "Comfortline", "Highline", "R-Line", "S", "SE", "SEL", "Alltrack"],
      "Arteon": ["Elegance", "R-Line", "R", "SE", "SEL"],
      "Tiguan": ["Trendline", "Comfortline", "Highline", "R-Line", "R", "S", "SE", "SEL", "Allspace"],
      "Touareg": ["Elegance", "R-Line", "R", "Sport", "SEL", "Executive", "Hybrid", "V10 TDI"],
      "ID.3": ["Pure", "Pro", "Pro S", "Tour", "Pro Performance"],
      "ID.4": ["Pure", "Pro", "Pro S", "GTX", "Standard", "AWD Pro"],
      "ID.6": ["Pure", "Pro", "Pro S", "Crozz", "X"],
      "Touran": ["Trendline", "Comfortline", "Highline", "R-Line"],
      "T-Roc": ["Trendline", "Comfortline", "Highline", "R-Line", "R"],
      "T-Cross": ["Trendline", "Comfortline", "Highline", "R-Line"],
      "Golf R": ["Standard", "20 Years"],
      "Golf GTI": ["S", "SE", "Autobahn", "40th Anniversary", "Clubsport"],
      "CC": ["Sport", "R-Line", "Executive"],
      "Beetle": ["S", "SE", "SEL", "R-Line", "Final Edition", "Convertible"],
      "Phaeton": ["W12", "V8", "V6 TDI"],
      "Eos": ["Komfort", "Sport", "Lux", "Executive"],
      "Atlas": ["S", "SE", "SEL", "R-Line", "Cross Sport"],
      "Taos": ["S", "SE", "SEL"],
      "ID.5": ["Pro", "Pro Performance", "GTX"],
      "ID.7": ["Pro", "Pro S", "GTX", "Tourer"],
      "ID. Buzz": ["Pro", "Pro S", "GTX"],
      "Sharan": ["Trendline", "Comfortline", "Highline"],
      "Caddy": ["Cargo", "Maxi", "Beach", "California"],
      "Transporter": ["T6", "T6.1", "T7", "California", "Multivan"],
      "Amarok": ["Standard", "Highline", "Aventura"],
      "Other": ["Specify in title/description"]
    },
    "Volvo": {
      "S60": ["B4 Momentum", "B4 R-Design", "B5 R-Design", "B6 R-Design", "Recharge T8", "Core", "Plus", "Ultimate", "Polestar Engineered", "Recharge"],
      "S90": ["B5 Momentum", "B5 R-Design", "B6 Inscription", "Recharge T8", "Core", "Plus", "Ultimate", "Recharge"],
      "V60": ["B4 Momentum", "B4 R-Design", "B5 R-Design", "Recharge T8", "Cross Country", "Core", "Plus", "Polestar"],
      "V90": ["B5 Momentum", "B5 R-Design", "B6 Inscription", "Recharge T8", "Cross Country", "Core", "Plus"],
      "XC40": ["B3 Core", "B4 Core", "B4 Plus", "B5 Plus", "Recharge Pure Electric", "Recharge Twin", "Core", "Plus", "Ultimate", "Recharge"],
      "XC60": ["B4 Core", "B4 Plus", "B5 Plus", "B6 Ultimate", "Recharge T6", "Recharge T8", "Core", "Plus", "Ultimate", "Polestar Engineered", "Recharge"],
      "XC90": ["B5 Core", "B5 Plus", "B6 Plus", "B6 Ultimate", "Recharge T8", "Core", "Plus", "Ultimate", "Recharge", "Polestar"],
      "EX30": ["Single Motor", "Twin Motor", "Performance"],
      "EX40": ["Plus", "Ultimate", "Single Motor"],
      "EX90": ["Plus", "Ultimate", "Twin Motor Performance"],
      "C40": ["Core", "Plus", "Ultimate", "Recharge"],
      "EC40": ["Plus", "Ultimate"],
      "C30": ["Standard", "R-Design", "Polestar"],
      "C70": ["T5", "Inscription", "Convertible"],
      "S40": ["Standard", "R-Design"],
      "V40": ["Standard", "R-Design", "Cross Country"],
      "240": ["DL", "GL", "Turbo", "Wagon"],
      "740": ["GL", "GLE", "Turbo", "Wagon"],
      "850": ["Standard", "T5", "T5-R", "R", "Wagon"],
      "Other": ["Specify in title/description"]
    },
    "Xiaomi": {
      "SU7": ["Standard", "Pro", "Max"],
      "SU7 Ultra": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Zeekr": {
      "001": ["Standard", "Long Range", "Performance"],
      "007": ["Standard", "Long Range", "Performance"],
      "009": ["Standard", "Premium"],
      "X": ["Standard", "Premium"],
      "Other": ["Specify in title/description"]
    },
    "Bugatti": {
      "Chiron": ["Standard", "Sport", "Super Sport", "Pur Sport", "Profil\u00e9e"],
      "Veyron": ["Standard", "Grand Sport", "Super Sport", "Grand Sport Vitesse"],
      "Divo": ["Standard"],
      "Bolide": ["Standard"],
      "Tourbillon": ["Standard"],
      "EB110": ["GT", "SS"],
      "Mistral": ["Standard"],
      "Centodieci": ["Standard"],
      "La Voiture Noire": ["Standard"],
      "Veyron Super Sport": ["Standard", "World Record Edition"],
      "Veyron Grand Sport": ["Standard", "Vitesse"],
      "Other": ["Specify in title/description"]
    },
    "Cupra": {
      "Ateca": ["Standard", "VZ"],
      "Formentor": ["Standard", "VZ", "VZ5"],
      "Born": ["Standard", "e-Boost"],
      "Leon": ["Standard", "VZ"],
      "Terramar": ["Standard", "VZ"],
      "Other": ["Specify in title/description"]
    },
    "Daihatsu": {
      "Terios": ["Standard", "Luxury"],
      "Rocky": ["Standard", "Luxury"],
      "Sirion": ["Standard", "Luxury"],
      "Other": ["Specify in title/description"]
    },
    "EXEED": {
      "TXL": ["Standard", "Luxury"],
      "VX": ["Standard", "Luxury"],
      "RX": ["Standard", "Luxury"],
      "Other": ["Specify in title/description"]
    },
    "Foton": {
      "Tunland": ["Standard", "Luxury"],
      "Sauvana": ["Standard", "Luxury"],
      "Other": ["Specify in title/description"]
    },
    "Geely": {
      "Coolray": ["Standard", "Sport"],
      "Emgrand": ["Standard", "Luxury"],
      "Azkarra": ["Standard", "Luxury"],
      "Okavango": ["Standard", "Luxury"],
      "Other": ["Specify in title/description"]
    },
    "Hino": {
      "300 Series": ["Standard"],
      "500 Series": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Hongqi": {
      "H5": ["Standard", "Luxury"],
      "H9": ["Standard", "Luxury", "Plus"],
      "E-HS9": ["Standard", "Luxury"],
      "Other": ["Specify in title/description"]
    },
    "Ineos": {
      "Grenadier": ["Standard", "Fieldmaster", "Trialmaster"],
      "Other": ["Specify in title/description"]
    },
    "Karma": {
      "Revero": ["GT", "GTS"],
      "GS-6": ["Standard", "Sport"],
      "Other": ["Specify in title/description"]
    },
    "Koenigsegg": {
      "Agera": ["Standard", "R", "RS", "Final"],
      "Regera": ["Standard"],
      "Jesko": ["Standard", "Absolut"],
      "Gemera": ["Standard"],
      "CCR": ["Standard"],
      "CCX": ["Standard", "R"],
      "One:1": ["Standard"],
      "CC8S": ["Standard"],
      "CC850": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Lada": {
      "Niva": ["Standard", "Legend", "Travel"],
      "Granta": ["Standard", "Sport"],
      "Other": ["Specify in title/description"]
    },
    "Lancia": {
      "Ypsilon": ["Silver", "Gold", "Platinum"],
      "Delta": ["Standard", "Integrale"],
      "Other": ["Specify in title/description"]
    },
    "Lotus": {
      "Emira": ["V6 First Edition", "V6 Sport", "i4 First Edition"],
      "Evija": ["Standard"],
      "Eletre": ["Standard", "S", "R"],
      "Esprit": ["S1", "S2", "S3", "Turbo", "V8", "Sport 350"],
      "Elise": ["S", "R", "Sprint", "Cup 250", "Cup 260"],
      "Exige": ["S", "Cup", "Sport 350", "Sport 410", "Cup 430", "Sport 240 Final Edition"],
      "Evora": ["S", "Sport 410", "GT430", "400", "410"],
      "Europa": ["S", "SE"],
      "Elan": ["S1", "S2", "Sprint", "M100"],
      "Excel": ["SE", "SA"],
      "Other": ["Specify in title/description"]
    },
    "MINI": {
      "Cooper": ["Standard", "S", "SE", "JCW"],
      "Clubman": ["Cooper", "Cooper S", "JCW"],
      "Countryman": ["Cooper", "Cooper S", "Cooper SE", "JCW"],
      "Convertible": ["Cooper", "Cooper S", "JCW"],
      "Aceman": ["Standard", "S"],
      "Other": ["Specify in title/description"]
    },
    "Opel": {
      "Astra": ["Edition", "GS", "GS Line", "OPC"],
      "Corsa": ["Edition", "GS", "GS Line", "Electric"],
      "Crossland": ["Edition", "GS", "GS Line"],
      "Grandland": ["Edition", "GS", "GS Line", "PHEV"],
      "Insignia": ["Edition", "GS", "GS Line"],
      "Mokka": ["Edition", "GS", "GS Line", "Electric"],
      "Other": ["Specify in title/description"]
    },
    "Pagani": {
      "Huayra": ["Standard", "BC", "Roadster", "Roadster BC", "Tricolore"],
      "Utopia": ["Standard"],
      "Zonda": ["C12", "S", "F", "Roadster", "Cinque", "Tricolore", "Revolucion", "HP Barchetta"],
      "Imola": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Proton": {
      "X50": ["Standard", "Executive", "Premium", "Flagship"],
      "X70": ["Standard", "Executive", "Premium", "Flagship"],
      "Saga": ["Standard", "Premium"],
      "Persona": ["Standard", "Premium"],
      "Other": ["Specify in title/description"]
    },
    "Rivian": {
      "R1T": ["Adventure", "Explore", "Launch Edition"],
      "R1S": ["Adventure", "Explore", "Launch Edition"],
      "Other": ["Specify in title/description"]
    },
    "SEAT": {
      "Ibiza": ["Reference", "Style", "FR"],
      "Arona": ["Reference", "Style", "Xperience", "FR"],
      "Ateca": ["Reference", "Style", "Xperience", "FR"],
      "Leon": ["Reference", "Style", "FR", "Cupra"],
      "Tarraco": ["Reference", "Style", "Xperience", "FR"],
      "Other": ["Specify in title/description"]
    },
    "Smart": {
      "#1": ["Pro", "Premium", "Brabus"],
      "#3": ["Pro", "Premium", "Brabus"],
      "Fortwo": ["Pure", "Passion", "Prime", "Brabus"],
      "Forfour": ["Pure", "Passion", "Prime", "Brabus"],
      "Other": ["Specify in title/description"]
    },
    "Wuling": {
      "Air EV": ["Standard", "Long Range"],
      "Almaz": ["Standard", "Exclusive"],
      "Cortez": ["Standard", "Exclusive"],
      "Other": ["Specify in title/description"]
    },
    "Other": {
      "Other": ["Other"]
    }
  },

  /* ══════════════════════════════════════════════════════════════════════════
     BOATS
  ══════════════════════════════════════════════════════════════════════════ */
  boats: {
    "Azimut": {
      "Azimut 40": ["Standard", "Fly"],
      "Azimut 50": ["Standard", "Fly"],
      "Azimut 60": ["Standard", "Fly"],
      "Azimut 70": ["Standard", "Fly"],
      "Azimut 80": ["Standard", "Fly"],
      "Azimut 100": ["Standard", "Fly"],
      "Azimut 120": ["Standard"],
      "S6": ["Standard"],
      "S7": ["Standard"],
      "S8": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Benetti": {
      "Delfino 93": ["Standard"],
      "Classic 120": ["Standard"],
      "Classic 140": ["Standard"],
      "Classic 165": ["Standard"],
      "Oasis 40M": ["Standard"],
      "Oasis 50M": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Boston Whaler": {
      "170 Montauk": ["Standard"],
      "190 Montauk": ["Standard"],
      "210 Montauk": ["Standard"],
      "270 Vantage": ["Standard"],
      "280 Outrage": ["Standard"],
      "320 Vantage": ["Standard"],
      "350 Outrage": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Bayliner": {
      "Element E16": ["Standard"],
      "Element E18": ["Standard"],
      "VR4": ["Standard", "Bowrider"],
      "VR5": ["Standard", "Bowrider"],
      "VR6": ["Standard", "Bowrider"],
      "Trophy 19CC": ["Standard"],
      "Trophy 21CC": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Ferretti": {
      "Ferretti 500": ["Standard", "Fly"],
      "Ferretti 550": ["Standard", "Fly"],
      "Ferretti 670": ["Standard", "Fly"],
      "Ferretti 720": ["Standard", "Fly"],
      "Ferretti 780": ["Standard", "Fly"],
      "Ferretti 850": ["Standard", "Fly"],
      "Ferretti 920": ["Standard", "Fly"],
      "Other": ["Specify in title/description"]
    },
    "Gulf Craft": {
      "Oryx 24": ["Standard"],
      "Oryx 28": ["Standard"],
      "Oryx 32": ["Standard"],
      "Oryx 36": ["Standard"],
      "Oryx 40": ["Standard"],
      "Oryx 43": ["Standard"],
      "Touring 22": ["Standard"],
      "Touring 26": ["Standard"],
      "Touring 30": ["Standard"],
      "Majesty 48": ["Standard"],
      "Majesty 55": ["Standard"],
      "Majesty 62": ["Standard"],
      "Majesty 75": ["Standard"],
      "Majesty 100": ["Standard"],
      "Majesty 120": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Jeanneau": {
      "Cap Camarat 5.5": ["WA", "CC", "BR"],
      "Cap Camarat 6.5": ["WA", "CC", "BR"],
      "Cap Camarat 7.5": ["WA", "CC"],
      "Cap Camarat 9.0": ["WA", "CC"],
      "Merry Fisher 695": ["Standard", "Marlin"],
      "Merry Fisher 795": ["Standard", "Marlin"],
      "Merry Fisher 895": ["Standard", "Marlin"],
      "Sun Odyssey 380": ["Standard"],
      "Sun Odyssey 410": ["Standard"],
      "Sun Odyssey 440": ["Standard"],
      "Sun Odyssey 490": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "L\u00fcrssen": {
      "44M": ["Standard"],
      "60M": ["Standard"],
      "80M": ["Standard"],
      "100M": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Majesty Yachts": {
      "Majesty 48": ["Standard"],
      "Majesty 55": ["Standard"],
      "Majesty 62": ["Standard"],
      "Majesty 75": ["Standard"],
      "Majesty 100": ["Standard"],
      "Majesty 120": ["Standard"],
      "Majesty 140": ["Standard"],
      "Majesty 175": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Nimbus": {
      "T8": ["Standard"],
      "T9": ["Standard"],
      "T11": ["Standard"],
      "305 Coup\u00e9": ["Standard"],
      "405 Coup\u00e9": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Nomad": {
      "Nomad 55": ["Standard"],
      "Nomad 65": ["Standard"],
      "Nomad 75": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Oceanos": {
      "Oceanos 40": ["Standard", "Fly"],
      "Oceanos 50": ["Standard", "Fly"],
      "Oceanos 60": ["Standard", "Fly"],
      "Other": ["Specify in title/description"]
    },
    "Princess": {
      "V40": ["Standard", "Open"],
      "V50": ["Standard", "Open"],
      "V55": ["Standard", "Open"],
      "V60": ["Standard", "Open"],
      "V65": ["Standard", "Open"],
      "V78": ["Standard", "Open"],
      "Y72": ["Standard"],
      "Y85": ["Standard"],
      "Y95": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Riva": {
      "Aquariva Super": ["Standard"],
      "Rivamare": ["Standard"],
      "Rivale 56": ["Standard"],
      "Dolceriva": ["Standard"],
      "El-Iseo": ["Standard"],
      "Riva 76": ["Bahamas", "Bahamas Super"],
      "Riva 88": ["Florida", "Florida Super"],
      "Riva 100": ["Corsaro", "Corsaro Super"],
      "Other": ["Specify in title/description"]
    },
    "Sea Ray": {
      "190 SPX": ["Standard"],
      "210 SPX": ["Standard"],
      "230 SLX": ["Standard"],
      "270 SLX": ["Standard"],
      "310 SLX": ["Standard"],
      "350 SLX": ["Standard"],
      "400 SLX": ["Standard"],
      "Sundancer 260": ["Standard"],
      "Sundancer 320": ["Standard"],
      "Sundancer 350": ["Standard"],
      "Sundancer 400": ["Standard"],
      "Sundancer 460": ["Standard"],
      "Sundancer 520": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Sunseeker": {
      "Predator 55": ["Standard"],
      "Predator 65": ["Standard"],
      "Predator 74": ["Standard"],
      "Manhattan 55": ["Standard"],
      "Manhattan 65": ["Standard"],
      "Manhattan 75": ["Standard"],
      "Yacht 75": ["Standard"],
      "Yacht 88": ["Standard"],
      "Yacht 95": ["Standard"],
      "Ocean 182": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Technomar": {
      "Technomar 40": ["Standard"],
      "Technomar 50": ["Standard"],
      "Technomar 65": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Yamaha": {
      "242 Limited S": ["Standard"],
      "252S": ["Standard"],
      "275SD": ["Standard"],
      "AR190": ["Standard"],
      "AR210": ["Standard"],
      "AR240": ["Standard"],
      "SX190": ["Standard"],
      "SX210": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Other": {
      "Other": ["Other"]
    }
  },

  /* ══════════════════════════════════════════════════════════════════════════
     BIKES
  ══════════════════════════════════════════════════════════════════════════ */
  bikes: {
    "BMW Motorrad": {
      "R 1250 GS": ["Standard", "Adventure", "Trophy", "40 Years GS"],
      "R 1250 RT": ["Standard", "SE"],
      "R 1250 RS": ["Standard", "SE"],
      "R 1250 R": ["Standard", "Exclusive"],
      "S 1000 RR": ["Standard", "M Sport", "M Competition"],
      "S 1000 R": ["Standard", "M Sport"],
      "S 1000 XR": ["Standard", "Sport", "Pro"],
      "F 900 R": ["Standard", "A2"],
      "F 900 XR": ["Standard", "A2"],
      "F 850 GS": ["Standard", "Adventure", "Trophy"],
      "F 750 GS": ["Standard"],
      "G 310 R": ["Standard"],
      "G 310 GS": ["Standard"],
      "K 1600 GT": ["Standard", "SE"],
      "K 1600 GTL": ["Standard", "Exclusive"],
      "M 1000 RR": ["Standard", "Competition"],
      "CE 04": ["Standard", "Connect Ride"],
      "Other": ["Specify in title/description"]
    },
    "Ducati": {
      "Panigale V4": ["Standard", "S", "R", "SP", "SP2", "Superleggera"],
      "Panigale V2": ["Standard", "Bayliss", "Winter Test"],
      "Streetfighter V4": ["Standard", "S", "SP", "SP2", "Lamborghini"],
      "Streetfighter V2": ["Standard", "B"],
      "Multistrada V4": ["Standard", "S", "S Sport", "Rally", "Rally Pro", "Pikes Peak"],
      "Multistrada V2": ["Standard", "S", "S Sport", "Rally"],
      "Monster": ["Standard", "Plus", "SP"],
      "SuperSport": ["950", "950 S"],
      "Diavel V4": ["Standard", "Lamborghini"],
      "XDiavel": ["Standard", "S", "Dark", "NQ", "Nera", "Black Star"],
      "Scrambler": ["Icon", "Icon Dark", "Urban Motard", "Full Throttle", "Desert Sled", "Nightshift", "1100 Pro", "1100 Sport Pro", "1100 Tribute Pro", "Cafe Racer", "1100"],
      "Hypermotard": ["950", "950 SP", "950 RVE"],
      "DesertX": ["Standard", "Rally"],
      "Elettrica": ["Standard"],
      "1198": ["Standard", "S", "R", "SP", "Corse"],
      "1199 Panigale": ["Standard", "S", "R", "Tricolore", "Superleggera"],
      "1299 Panigale": ["Standard", "S", "R", "Final Edition", "Superleggera"],
      "999": ["Standard", "S", "R", "Monoposto", "Biposto"],
      "996": ["Standard", "S", "SPS", "R"],
      "916": ["Standard", "SP", "SPS", "Senna"],
      "888": ["Standard", "SP4", "SP5"],
      "Hypermotard 950": ["Standard", "SP", "RVE"],
      "Multistrada 1260": ["Standard", "S", "Pikes Peak", "Enduro"],
      "Diavel 1260": ["Standard", "S", "Lamborghini"],
      "Monster 821": ["Standard", "Stripe", "Stealth"],
      "Monster 1200": ["Standard", "S", "R", "25 Anniversario"],
      "Monster 696": ["Standard", "ABS"],
      "SuperSport 939": ["Standard", "S"],
      "Other": ["Specify in title/description"]
    },
    "Harley-Davidson": {
      "Sportster S": ["Standard", "Iron 883", "Iron 1200", "Forty-Eight", "Roadster", "Nightster"],
      "Nightster": ["Standard", "Special"],
      "Iron 883": ["Standard", "Dark Custom"],
      "Iron 1200": ["Standard"],
      "Forty-Eight": ["Standard"],
      "Street Bob 114": ["Standard"],
      "Fat Bob 114": ["Standard"],
      "Low Rider S": ["Standard"],
      "Low Rider ST": ["Standard"],
      "Softail Standard": ["Standard"],
      "Heritage Classic 114": ["Standard"],
      "Fat Boy 114": ["Standard"],
      "Breakout 117": ["Standard"],
      "Road Glide": ["Standard", "Special", "ST", "Limited", "Anniversary", "CVO"],
      "Street Glide": ["Standard", "Special", "ST", "Anniversary", "Limited", "CVO"],
      "Road King": ["Standard", "Special", "Classic"],
      "Electra Glide": ["Standard", "Ultra Classic", "Ultra Limited", "Ultra Limited Low", "Revival", "Highway King"],
      "CVO Road Glide": ["Standard", "Limited"],
      "CVO Street Glide": ["Standard"],
      "Pan America 1250": ["Standard", "Special"],
      "Street Bob": ["Standard", "114", "FXBB"],
      "Fat Bob": ["Standard", "114"],
      "Fat Boy": ["Standard", "114", "Anniversary"],
      "Heritage Classic": ["Standard", "114", "Anniversary"],
      "Softail Slim": ["Standard"],
      "Breakout": ["Standard", "114", "117"],
      "Low Rider": ["Standard", "S", "ST", "El Diablo"],
      "Ultra Limited": ["Standard", "Anniversary"],
      "Pan America": ["1250", "1250 Special"],
      "LiveWire": ["Standard", "ONE", "S2 Del Mar"],
      "V-Rod": ["Muscle", "Night Rod", "Night Rod Special", "VRSCAW"],
      "Other": ["Specify in title/description"]
    },
    "Honda": {
      "CBR 650R": ["Standard", "E-Clutch"],
      "CBR 1000RR-R Fireblade": ["Standard", "SP"],
      "CBR 500R": ["Standard"],
      "CB 650R": ["Standard", "E-Clutch"],
      "CB 1000R": ["Standard", "Black Edition"],
      "CB 500F": ["Standard"],
      "CB 500X": ["Standard"],
      "CB 300R": ["Standard"],
      "Africa Twin": ["Standard", "Adventure Sports", "Adventure Sports ES", "DCT", "ES"],
      "NC 750X": ["Standard", "DCT"],
      "NC 750S": ["Standard", "DCT"],
      "X-ADV": ["Standard"],
      "Forza 750": ["Standard"],
      "Forza 350": ["Standard"],
      "Forza 125": ["Standard"],
      "Gold Wing": ["Standard", "Tour", "Tour DCT", "Tour Airbag DCT", "DCT", "Airbag"],
      "Rebel 500": ["Standard", "ABS", "SE"],
      "Rebel 1100": ["Standard", "DCT", "T"],
      "CBR1000RR": ["Standard", "SP", "SP2", "Fireblade", "Fireblade SP"],
      "CBR1000RR-R": ["Standard", "SP", "Fireblade", "WSBK"],
      "CBR600RR": ["Standard", "ABS", "SP"],
      "CBR650R": ["Standard", "E-Clutch", "ABS"],
      "CBR500R": ["Standard", "ABS"],
      "CBR300R": ["Standard", "ABS"],
      "CB1000R": ["Standard", "Black Edition", "Neo Sports Cafe"],
      "CB650R": ["Standard", "E-Clutch"],
      "CB500F": ["Standard"],
      "CB300R": ["Standard", "ABS"],
      "VFR1200X": ["Standard", "Crosstourer"],
      "CRF1100L": ["Standard", "Adventure Sports"],
      "Other": ["Specify in title/description"]
    },
    "Kawasaki": {
      "Ninja ZX-10R": ["Standard", "SE", "KRT Edition"],
      "Ninja ZX-6R": ["Standard", "KRT Edition"],
      "Ninja 650": ["Standard", "KRT Edition", "KRT", "Tourer"],
      "Ninja 400": ["Standard", "KRT Edition", "KRT", "Performance"],
      "Z900": ["Standard", "SE", "RS", "RS SE", "RS Cafe"],
      "Z650": ["Standard", "RS"],
      "Z400": ["Standard", "SE"],
      "Versys 1000": ["Standard", "SE", "Grand Tourer", "LT", "S", "SE LT"],
      "Versys 650": ["Standard", "LT", "Tourer"],
      "KLR 650": ["Standard", "Adventure"],
      "W800": ["Standard", "Cafe", "Street"],
      "Eliminator": ["Standard", "SE"],
      "Vulcan S": ["Standard", "ABS", "Cafe", "Tourer"],
      "H2": ["Standard", "Carbon", "SX", "SX SE", "SX SE+"],
      "H2R": ["Standard"],
      "ZX-10R": ["Standard", "KRT", "SE", "R", "RR"],
      "ZX-10RR": ["Standard", "WSBK Replica"],
      "Ninja H2": ["Standard", "Carbon", "R", "SX", "SX SE"],
      "Ninja H2R": ["Standard"],
      "Ninja 1000": ["Standard", "SX", "ABS"],
      "Ninja 300": ["Standard", "ABS", "SE"],
      "ZX-6R": ["Standard", "KRT", "R", "SE"],
      "ZX-14R": ["Standard", "ABS", "SE"],
      "Z H2": ["Standard", "SE"],
      "Z1000": ["Standard", "ABS", "SX"],
      "KX450": ["Standard", "XC", "X"],
      "KLR650": ["Standard", "S", "Traveler", "Adventure"],
      "Vulcan 900": ["Classic", "Custom", "Classic LT"],
      "Other": ["Specify in title/description"]
    },
    "KTM": {
      "Duke 125": ["Standard"],
      "Duke 200": ["Standard"],
      "Duke 390": ["Standard"],
      "Duke 790": ["Standard"],
      "Duke 890": ["Standard", "R"],
      "Duke 1290 Super": ["Standard", "S", "R"],
      "RC 125": ["Standard"],
      "RC 390": ["Standard", "Cup"],
      "Adventure 390": ["Standard"],
      "Adventure 790": ["Standard", "R"],
      "Adventure 890": ["Standard", "R", "Rally", "Rally Factory"],
      "Adventure 1090": ["Standard", "R"],
      "Adventure 1190": ["Standard", "R"],
      "Adventure 1290 Super": ["Standard", "S", "R"],
      "SMC R 690": ["Standard"],
      "EXC 300": ["Standard", "TPI"],
      "EXC-F 350": ["Standard", "Six Days"],
      "EXC-F 450": ["Standard", "Six Days"],
      "1290 Super Duke R": ["Standard", "RR", "Evo"],
      "890 Duke R": ["Standard"],
      "790 Duke": ["Standard", "L"],
      "390 Duke": ["Standard"],
      "200 Duke": ["Standard"],
      "125 Duke": ["Standard"],
      "RC 8C": ["Standard"],
      "1290 Super Adventure": ["S", "R", "T"],
      "890 Adventure": ["Standard", "R", "R Rally"],
      "790 Adventure": ["Standard", "R", "R Rally"],
      "390 Adventure": ["Standard", "Rally"],
      "450 EXC-F": ["Standard", "Six Days"],
      "Freeride E-XC": ["Standard"],
      "Other": ["Specify in title/description"]
    },
    "Suzuki": {
      "GSX-R 600": ["Standard"],
      "GSX-R 750": ["Standard"],
      "GSX-R 1000": ["Standard", "R"],
      "GSX-S 750": ["Standard"],
      "GSX-S 1000": ["Standard", "GT", "GT+"],
      "GSX-S 950": ["Standard"],
      "V-Strom 650": ["Standard", "XT"],
      "V-Strom 1050": ["Standard", "XT", "DE"],
      "Burgman 400": ["Standard"],
      "Burgman 650": ["Standard", "Executive"],
      "Boulevard M109R": ["Standard", "B.O.S.S."],
      "Boulevard C90": ["Standard", "T"],
      "Hayabusa": ["Standard", "Limited Edition", "25th Anniversary"],
      "GSX-R1000": ["Standard", "R", "R Phantom", "Anniversary"],
      "GSX-R750": ["Standard", "Anniversary"],
      "GSX-R600": ["Standard", "Anniversary"],
      "GSX-S1000": ["Standard", "GT", "F"],
      "GSX-S750": ["Standard", "Anniversary"],
      "GSX-8S": ["Standard"],
      "GSX-8R": ["Standard"],
      "Katana": ["Standard"],
      "SV650": ["Standard", "S", "X"],
      "V-Strom 800": ["DE", "Touring"],
      "Other": ["Specify in title/description"]
    },
    "Triumph": {
      "Street Triple": ["R", "RS", "Moto2 Edition", "765 S", "765 R", "765 RS", "765 Moto2 Edition"],
      "Speed Triple": ["1200 RS", "1200 RR", "R", "RX", "S"],
      "Tiger 660": ["Sport"],
      "Tiger 900": ["GT", "GT Pro", "GT Low", "Rally", "Rally Pro", "Rally Explorer", "Arag\u00f3n Edition"],
      "Tiger 1200": ["GT", "GT Pro", "GT Explorer", "Rally", "Rally Pro", "Rally Explorer"],
      "Bonneville T100": ["Standard", "Black", "Bud Ekins", "Stealth Edition"],
      "Bonneville T120": ["Standard", "Black", "Gold Line", "Bud Ekins"],
      "Bonneville Bobber": ["Standard", "Black"],
      "Bonneville Speedmaster": ["Standard", "Stealth"],
      "Thruxton RS": ["Standard", "Moto2 Edition"],
      "Scrambler 400 X": ["Standard"],
      "Scrambler 900": ["Standard", "Classic", "Gold Line"],
      "Scrambler 1200": ["XC", "XE", "Bond Edition", "X", "Steve McQueen"],
      "Rocket 3": ["R", "GT", "Storm", "TFC"],
      "Trident 660": ["Standard"],
      "Daytona 660": ["Standard", "Moto2 Edition"],
      "Speed 400": ["Standard"],
      "Daytona 675": ["Standard", "R", "Triple R"],
      "Daytona 765": ["Moto2", "Limited Edition"],
      "Tiger 850 Sport": ["Standard"],
      "Thruxton": ["1200", "1200 RS", "R", "Final Edition"],
      "Other": ["Specify in title/description"]
    },
    "Yamaha": {
      "YZF-R1": ["Standard", "M", "GYTR"],
      "YZF-R6": ["Standard", "Race"],
      "YZF-R7": ["Standard", "World GP 60th"],
      "YZF-R3": ["Standard", "Monster Energy MotoGP", "World GP 60th"],
      "MT-10": ["Standard", "SP"],
      "MT-09": ["Standard", "SP", "Tracer GT", "Tracer GT+"],
      "MT-07": ["Standard", "Tracer GT"],
      "MT-03": ["Standard"],
      "MT-125": ["Standard"],
      "XSR 900": ["Standard", "GP"],
      "XSR 700": ["Standard"],
      "XSR 125": ["Standard"],
      "T\u00e9n\u00e9r\u00e9 700": ["Standard", "World Raid"],
      "T\u00e9n\u00e9r\u00e9 700 Explore": ["Standard"],
      "NMAX 155": ["Standard", "Connected"],
      "XMAX 300": ["Standard", "Tech MAX"],
      "XMAX 400": ["Standard", "Tech MAX"],
      "TMAX 560": ["Standard", "Tech MAX"],
      "Tracer 9": ["Standard", "GT", "GT+"],
      "FJR 1300": ["A", "AS"],
      "V-Star 250": ["Standard"],
      "V-Star 650": ["Standard", "Custom", "Silverado"],
      "V-Star 950": ["Standard", "Tourer"],
      "V-Star 1300": ["Standard", "Tourer", "Deluxe"],
      "Bolt": ["Standard", "R-Spec", "C-Spec"],
      "YZF-R1M": ["Standard", "60th Anniversary"],
      "YZF-R125": ["Standard", "World GP 60th"],
      "MT-01": ["Standard"],
      "MT-25": ["Standard"],
      "FZ-09": ["Standard"],
      "FZ-10": ["Standard"],
      "FJR1300": ["Standard", "ES", "AS"],
      "Tracer 7": ["Standard", "GT"],
      "Tenere 700": ["Standard", "World Raid", "Rally Edition"],
      "Super Tenere": ["Standard", "ES", "Raid Edition"],
      "VMAX": ["Standard", "Carbon"],
      "V-Star": ["250", "650", "950", "1100", "1300"],
      "XJR1300": ["Standard", "Racer"],
      "XSR700": ["Standard", "Legacy"],
      "XSR900": ["Standard", "GP"],
      "Other": ["Specify in title/description"]
    },
    "Other": {
      "Other": ["Other"]
    },
    "BMW": {
      "S1000R": ["Standard", "M Package", "Sport"],
      "S1000XR": ["Standard", "TE", "M Package"],
      "K1300S": ["Standard", "HP", "Sport"],
      "K1300R": ["Standard", "HP"],
      "K1600GT": ["Standard", "Sport", "Bagger"],
      "K1600B": ["Standard", "Grand America"],
      "R1100GS": ["Standard", "Adventure"],
      "R1150GS": ["Standard", "Adventure"],
      "R1200GS": ["Standard", "Adventure", "Rallye"],
      "HP4 Race": ["Standard"],
      "F900R": ["Standard", "Premium"],
      "F900XR": ["Standard", "TE", "Premium"],
      "F850GS": ["Standard", "Adventure", "TE"],
      "F750GS": ["Standard", "TE"],
      "G310R": ["Standard"],
      "G310GS": ["Standard"],
      "C400X": ["Standard"],
      "C400GT": ["Standard"],
      "CE 04": ["Standard"],
      "R nineT": ["Pure", "Racer", "Scrambler", "Urban G/S", "Roadster", "100 Years"],
      "Other": ["Specify in title/description"]
    },
    "Aprilia": {
      "RSV4": ["Factory", "RR", "XX", "SP"],
      "Tuono V4": ["Standard", "Factory", "RR", "X"],
      "RS 660": ["Standard", "Extrema"],
      "Tuono 660": ["Standard", "Factory"],
      "Shiver 900": ["Standard"],
      "Dorsoduro 900": ["Standard"],
      "SXV": ["450", "550"],
      "Caponord": ["1200 Rally", "1200 Travel"],
      "Other": ["Specify in title/description"]
    }
  },

  /* ══════════════════════════════════════════════════════════════════════════
     JETSKI
  ══════════════════════════════════════════════════════════════════════════ */
  jetski: {
    "Sea-Doo": {
      "Spark": ["2up 60hp", "2up 90hp", "3up 90hp", "Trixx 2up", "Trixx 3up"],
      "GTI": ["GTI 90", "GTI 130", "GTI SE 130", "GTI SE 170", "GTI Pro 130", "GTI Pro 170"],
      "GTR": ["GTR 230"],
      "GTX": ["GTX 170", "GTX 230", "GTX Limited 230", "GTX Limited 300"],
      "RXT": ["RXT 230", "RXT-X 300"],
      "RXP": ["RXP-X 300", "RXP-X Apex"],
      "Wake": ["Wake 170", "Wake Pro 230"],
      "Fish Pro": ["Fish Pro Scout 130", "Fish Pro Sport 170", "Fish Pro Trophy 170"],
      "Explorer Pro": ["130", "170"],
      "Switch": ["13 Sport", "13 Cruise", "18 Sport", "18 Cruise", "18 Cruise LE", "21 Cruise", "21 Cruise LE"],
      "Other": ["Specify in title/description"]
    },
    "Yamaha": {
      "EX": ["EX", "EX Sport", "EX Deluxe"],
      "VX": ["VX", "VX Cruiser", "VX Cruiser HO", "VX Limited HO"],
      "FX": ["FX Cruiser HO", "FX HO", "FX Cruiser SVHO", "FX SVHO", "FX Limited SVHO"],
      "GP": ["GP1800R HO", "GP1800R SVHO"],
      "SuperJet": ["Standard"],
      "WaveRunner FX": ["FX Cruiser HO", "FX HO", "FX SVHO", "FX Cruiser SVHO", "FX Limited SVHO"],
      "Other": ["Specify in title/description"]
    },
    "Kawasaki": {
      "Jet Ski Ultra": ["Ultra 160LX", "Ultra 310LX", "Ultra 310LX-S", "Ultra 310R", "Ultra 310X", "Ultra 310X-S"],
      "Jet Ski STX": ["STX 160", "STX 160X", "STX 160LX"],
      "Jet Ski SX-R": ["SX-R 160"],
      "Jet Ski Ultra 160": ["Standard", "LX"],
      "Jet Ski Ultra 310": ["Standard", "LX", "LX-S", "R", "X", "X-S"],
      "Other": ["Specify in title/description"]
    },
    "Honda": {
      "AquaTrax": ["F-12", "F-12X", "F-15X", "R-12", "R-12X"],
      "Other": ["Specify in title/description"]
    },
    "Polaris": {
      "SLTX": ["Standard"],
      "Virage": ["Standard", "TX", "TXi"],
      "Genesis": ["Standard", "FFI"],
      "Other": ["Specify in title/description"]
    },
    "Other": {
      "Other": ["Other"]
    }
  },

  /* ══════════════════════════════════════════════════════════════════════════
     HEAVY
  ══════════════════════════════════════════════════════════════════════════ */
  heavy: {
    "Mercedes-Benz": {
      "Actros": ["1840", "1845", "2040", "2045", "2545", "2645", "3345", "4145", "Other"],
      "Arocs": ["1830", "1835", "2040", "2045", "2645", "3240", "Other"],
      "Atego": ["816", "818", "1218", "1222", "1524", "1624", "Other"],
      "Axor": ["1840", "1845", "2040", "2045", "Other"],
      "Other": ["Specify in title/description"]
    },
    "Volvo": {
      "FH": ["FH16", "FH13", "FH 500", "FH 540", "FH 600", "Other"],
      "FM": ["FM 330", "FM 370", "FM 410", "FM 460", "Other"],
      "FMX": ["FMX 370", "FMX 410", "FMX 460", "Other"],
      "FL": ["FL 210", "FL 240", "FL 280", "Other"],
      "FE": ["FE 280", "FE 320", "Other"],
      "Other": ["Specify in title/description"]
    },
    "MAN": {
      "TGX": ["18.440", "18.480", "18.500", "26.440", "26.480", "33.440", "Other"],
      "TGS": ["18.360", "18.400", "26.360", "26.400", "33.360", "Other"],
      "TGM": ["12.180", "12.220", "15.180", "15.220", "Other"],
      "TGL": ["7.150", "7.180", "8.150", "8.180", "Other"],
      "Other": ["Specify in title/description"]
    },
    "Scania": {
      "R Series": ["R 410", "R 450", "R 500", "R 540", "R 580", "Other"],
      "S Series": ["S 410", "S 450", "S 500", "S 540", "S 580", "Other"],
      "G Series": ["G 360", "G 410", "G 450", "Other"],
      "P Series": ["P 230", "P 280", "P 320", "P 360", "Other"],
      "Other": ["Specify in title/description"]
    },
    "DAF": {
      "XF": ["XF 440", "XF 480", "XF 530", "Other"],
      "CF": ["CF 330", "CF 370", "CF 410", "Other"],
      "LF": ["LF 150", "LF 180", "LF 210", "Other"],
      "Other": ["Specify in title/description"]
    },
    "Iveco": {
      "Stralis": ["AS 440", "AS 480", "AS 500", "Other"],
      "Trakker": ["AT 330", "AT 360", "AT 410", "Other"],
      "Daily": ["35S", "50C", "65C", "70C", "Other"],
      "Other": ["Specify in title/description"]
    },
    "Renault": {
      "T Series": ["T 440", "T 480", "T 520", "Other"],
      "C Series": ["C 380", "C 430", "C 480", "Other"],
      "K Series": ["K 380", "K 430", "K 480", "Other"],
      "Other": ["Specify in title/description"]
    },
    "Hino": {
      "700 Series": ["SS", "SH", "FY", "Other"],
      "500 Series": ["FC", "FD", "GD", "GH", "GT", "Other"],
      "300 Series": ["WU", "XZU", "Other"],
      "Other": ["Specify in title/description"]
    },
    "Mitsubishi Fuso": {
      "Super Great": ["V", "FV", "FP", "FS", "FU", "Other"],
      "Fighter": ["FK", "FM", "Other"],
      "Canter": ["FE", "FG", "Other"],
      "Other": ["Specify in title/description"]
    },
    "Isuzu": {
      "Giga": ["CXZ", "EXZ", "FVZ", "GVZ", "Other"],
      "Forward": ["FRR", "FSR", "FTR", "FVR", "Other"],
      "Elf": ["NKR", "NMR", "NPR", "NQR", "NRR", "Other"],
      "Other": ["Specify in title/description"]
    },
    "Toyota": {
      "Dyna": ["150", "200", "Other"],
      "Coaster": ["Standard", "Other"],
      "Land Cruiser 70": ["Single Cab", "Double Cab", "Other"],
      "Other": ["Specify in title/description"]
    },
    "Ford": {
      "F-Series": ["F-650", "F-750", "Other"],
      "Transit": ["350", "350 HD", "Other"],
      "Other": ["Specify in title/description"]
    },
    "Caterpillar": {
      "Excavator": ["320", "323", "330", "336", "340", "Other"],
      "Bulldozer": ["D6", "D7", "D8", "D9", "Other"],
      "Wheel Loader": ["930", "938", "950", "962", "966", "972", "Other"],
      "Motor Grader": ["120", "140", "160", "Other"],
      "Other": ["Specify in title/description"]
    },
    "Komatsu": {
      "Excavator": ["PC200", "PC210", "PC300", "PC360", "PC400", "Other"],
      "Bulldozer": ["D51", "D61", "D65", "D85", "Other"],
      "Wheel Loader": ["WA250", "WA320", "WA380", "WA430", "Other"],
      "Other": ["Specify in title/description"]
    },
    "JCB": {
      "Backhoe Loader": ["3CX", "4CX", "Other"],
      "Excavator": ["JS130", "JS200", "JS260", "JS330", "Other"],
      "Telehandler": ["525", "530", "535", "540", "Other"],
      "Other": ["Specify in title/description"]
    },
    "Other": {
      "Other": ["Other"]
    }
  }

};

/* ─── HELPER: Get sorted makes for a category (Other always last) ─── */
function getDM_Makes(category) {
  const keys = Object.keys(DM_VEHICLES[category] || {});
  return keys.sort((a, b) => {
    if (a === 'Other') return 1;
    if (b === 'Other') return -1;
    return a.localeCompare(b);
  });
}

/* ─── HELPER: Get models for a make/category (Other always last) ─── */
function getDM_Models(category, make) {
  const cat = DM_VEHICLES[category] || {};
  const keys = Object.keys(cat[make] || {});
  return keys.sort((a, b) => {
    if (a === 'Other') return 1;
    if (b === 'Other') return -1;
    return a.localeCompare(b);
  });
}

/* ─── HELPER: Get trims for a make/model/category (Other always last) ─── */
function getDM_Trims(category, make, model) {
  const cat = DM_VEHICLES[category] || {};
  const trims = (cat[make] || {})[model] || [];
  return [...trims.filter(t => t !== 'Other'), 'Other'];
}
